function runCanonicalPurchaseP5A2PreparationRegressionCli(){
    const barang = BarangRepository.findAll().map(function(row){ return String(row[COL_BARANG.ID] || "").trim(); }).filter(Boolean)[0];
    const beforeStock = BarangRepository.getStock(barang), beforeLedger = StockLedgerRepository.sheet().getLastRow();
    const make = function(submissionId, qty){ return { submissionId : submissionId, supplier : "P5A2_TEST", noFaktur : "P5A2-" + submissionId, admin : "P5A2", keterangan : "P5A2 preparation", items : [{ kodeBarang : barang, qty : qty, hargaBeli : 10000 }, { kodeBarang : barang, qty : 2, hargaBeli : 10000 }] }; };
    const token = "P5A2-" + Date.now();
    const first = prepareCanonicalPurchaseSubmission(make(token, 1));
    const retry = prepareCanonicalPurchaseSubmission(make(token, 1));
    if(first.purchaseNumber !== retry.purchaseNumber || !retry.alreadyPrepared || PurchaseRepository.findItemsByPurchaseNumber(first.purchaseNumber).length !== 2){ throw new Error("Resume canonical Purchase gagal."); }
    let conflict = false; try{ prepareCanonicalPurchaseSubmission(make(token, 9)); }catch(error){ conflict = String(error.message).indexOf("conflict") >= 0; }
    if(!conflict){ throw new Error("Conflict payload canonical Purchase tidak ditolak."); }
    const different = prepareCanonicalPurchaseSubmission(make(token + "-B", 1));
    if(different.purchaseNumber === first.purchaseNumber || BarangRepository.getStock(barang) !== beforeStock || StockLedgerRepository.sheet().getLastRow() !== beforeLedger){ throw new Error("Preparation mengubah inventory atau nomor dokumen."); }
    return { success : true, test : "CANONICAL_PURCHASE_P5A2_PREPARATION", message : "PASS", purchaseNumber : first.purchaseNumber };
}

function runCanonicalPurchaseP5A2Status_(name, fn){
    const key = "CANONICAL_PURCHASE:P5A2:" + name;
    const store = PropertiesService.getScriptProperties();
    store.setProperty(key, JSON.stringify({ status : "RUNNING" }));
    try{ const result = fn(); store.setProperty(key, JSON.stringify({ status : "PASS", result : result })); return result; }
    catch(error){ store.setProperty(key, JSON.stringify({ status : "FAIL", error : String(error.message || error), stack : String(error.stack || "") })); throw error; }
}
function getCanonicalPurchaseP5A2StatusCli(name){ const raw = PropertiesService.getScriptProperties().getProperty("CANONICAL_PURCHASE:P5A2:" + name); return raw ? JSON.parse(raw) : { status : "NOT_RUN" }; }
function canonicalPurchaseP5A2Fixture_(suffix){ const barang = BarangRepository.findAll().map(function(r){return String(r[COL_BARANG.ID]||"").trim();}).filter(Boolean)[0]; const id="P5A2S-"+suffix+"-"+Date.now(); return { submissionId:id, supplier:"P5A2", noFaktur:id, admin:"P5A2", keterangan:"P5A2", items:[{kodeBarang:barang,qty:1,hargaBeli:10000},{kodeBarang:barang,qty:2,hargaBeli:10000}]}; }
function canonicalPurchaseP5A2Snapshot_(barangIds){ return { headerRows:PurchaseRepository.getHeaderSheet().getLastRow(), detailRows:PurchaseRepository.getDetailSheet().getLastRow(), ledgerRows:StockLedgerRepository.sheet().getLastRow(), stocks:barangIds.map(function(id){return BarangRepository.getStock(id);}) }; }
function canonicalPurchaseP5A2AssertSameSnapshot_(before, after){ if(before.headerRows!==after.headerRows||before.detailRows!==after.detailRows||before.ledgerRows!==after.ledgerRows||before.stocks.join("|")!==after.stocks.join("|")){throw new Error("Conflict menambah persistence atau mengubah inventory.");} }
function runCanonicalPurchaseP5A2NewCli(){ return runCanonicalPurchaseP5A2Status_("NEW",function(){ const p=canonicalPurchaseP5A2Fixture_("NEW"); const r=prepareCanonicalPurchaseSubmission(p); if(r.alreadyPrepared){throw new Error("Unexpected resume");} return {success:true,purchaseNumber:r.purchaseNumber,submissionId:p.submissionId};});}
function runCanonicalPurchaseP5A2ResumeCli(){ return runCanonicalPurchaseP5A2Status_("RESUME",function(){const p=canonicalPurchaseP5A2Fixture_("RESUME");const a=prepareCanonicalPurchaseSubmission(p),b=prepareCanonicalPurchaseSubmission(p);if(a.purchaseNumber!==b.purchaseNumber||!b.alreadyPrepared)throw new Error("Resume gagal");return {success:true,purchaseNumber:a.purchaseNumber};});}
function runCanonicalPurchaseP5A2ConflictQtyCli(){return runCanonicalPurchaseP5A2Status_("CONFLICT_QTY",function(){const p=canonicalPurchaseP5A2Fixture_("QTY");prepareCanonicalPurchaseSubmission(p);p.items[0].qty=9;try{prepareCanonicalPurchaseSubmission(p);}catch(e){return {success:true,conflict:true};}throw new Error("Conflict qty tidak ditolak");});}
function runCanonicalPurchaseP5A2SchemaReadCli(){return runCanonicalPurchaseP5A2Status_("SCHEMA",function(){const f=getPurchaseCanonicalSchemaPreflight_();if(f.header.missingAppendOnly.length||f.detail.missingAppendOnly.length)throw new Error("Schema canonical tidak lengkap");return {success:true,headerColumns:f.header.currentHeaders.length,detailColumns:f.detail.currentHeaders.length};});}
function runCanonicalPurchaseP5A2ConflictBarangCli(){return runCanonicalPurchaseP5A2Status_("CONFLICT_BARANG",function(){const p=canonicalPurchaseP5A2Fixture_("BARANG"),barangLain=BarangRepository.findAll().map(function(r){return String(r[COL_BARANG.ID]||"").trim();}).filter(function(id){return id&&id!==p.items[0].kodeBarang;})[0];if(!barangLain)throw new Error("Fixture Barang kedua tidak tersedia");prepareCanonicalPurchaseSubmission(p);const before=canonicalPurchaseP5A2Snapshot_([p.items[0].kodeBarang,barangLain]);p.items[0].kodeBarang=barangLain;try{prepareCanonicalPurchaseSubmission(p);}catch(e){const after=canonicalPurchaseP5A2Snapshot_([p.items[1].kodeBarang,barangLain]);canonicalPurchaseP5A2AssertSameSnapshot_(before,after);return {success:true,conflict:true};}throw new Error("Conflict Barang tidak ditolak");});}
function runCanonicalPurchaseP5A2ConflictHeaderCli(){return runCanonicalPurchaseP5A2Status_("CONFLICT_HEADER",function(){const p=canonicalPurchaseP5A2Fixture_("HEADER");prepareCanonicalPurchaseSubmission(p);const before=canonicalPurchaseP5A2Snapshot_([p.items[0].kodeBarang]);p.supplier="P5A2_CHANGED";try{prepareCanonicalPurchaseSubmission(p);}catch(e){const after=canonicalPurchaseP5A2Snapshot_([p.items[0].kodeBarang]);canonicalPurchaseP5A2AssertSameSnapshot_(before,after);return {success:true,conflict:true};}throw new Error("Conflict header tidak ditolak");});}
function runCanonicalPurchaseP5A2DifferentCli(){return runCanonicalPurchaseP5A2Status_("DIFFERENT",function(){const a=canonicalPurchaseP5A2Fixture_("DIFFERENT"),b=JSON.parse(JSON.stringify(a)),before=canonicalPurchaseP5A2Snapshot_([a.items[0].kodeBarang]);b.submissionId+="-B";const x=prepareCanonicalPurchaseSubmission(a),y=prepareCanonicalPurchaseSubmission(b),after=canonicalPurchaseP5A2Snapshot_([a.items[0].kodeBarang]),hx=PurchaseRepository.findByPurchaseNumber(x.purchaseNumber),hy=PurchaseRepository.findByPurchaseNumber(y.purchaseNumber),dx=PurchaseRepository.findItemsByPurchaseNumber(x.purchaseNumber),dy=PurchaseRepository.findItemsByPurchaseNumber(y.purchaseNumber);if(x.purchaseNumber===y.purchaseNumber||hx.submissionId===hy.submissionId||hx.idempotencyKey===hy.idempotencyKey||hx.transactionId===hy.transactionId||dx.length!==2||dy.length!==2||after.headerRows!==before.headerRows+2||after.detailRows!==before.detailRows+4||after.ledgerRows!==before.ledgerRows||after.stocks[0]!==before.stocks[0])throw new Error("Different submission tidak terpisah atau mengubah inventory");return {success:true,first:x.purchaseNumber,second:y.purchaseNumber};});}
function runCanonicalPurchaseP5A2DuplicateCli(){return runCanonicalPurchaseP5A2Status_("DUPLICATE",function(){const p=canonicalPurchaseP5A2Fixture_("DUP"),before=canonicalPurchaseP5A2Snapshot_([p.items[0].kodeBarang]),x=prepareCanonicalPurchaseSubmission(p),d=PurchaseRepository.findItemsByPurchaseNumber(x.purchaseNumber),after=canonicalPurchaseP5A2Snapshot_([p.items[0].kodeBarang]);if(d.length!==2||d[0].kodeBarang!==p.items[0].kodeBarang||d[1].kodeBarang!==p.items[1].kodeBarang||Number(d[0].qty)!==1||Number(d[1].qty)!==2||d[0].lineId!==x.purchaseNumber+":L001"||d[1].lineId!==x.purchaseNumber+":L002"||after.headerRows!==before.headerRows+1||after.detailRows!==before.detailRows+2||after.ledgerRows!==before.ledgerRows||after.stocks[0]!==before.stocks[0])throw new Error("Line duplicate tidak line-preserving atau mengubah inventory");return {success:true,lineIds:d.map(function(i){return i.lineId;})};});}
function runCanonicalPurchaseP5A2HistoricalCli(){return runCanonicalPurchaseP5A2Status_("HISTORICAL",function(){const s=PurchaseRepository.getHeaderSheet(),c=PurchaseRepository.getColumnMap_(s),rows=s.getDataRange().getValues().slice(1),r=rows.find(function(x){return !String(x[c.SubmissionId]||"").trim();});if(!r)throw new Error("Historical Purchase tidak ditemukan");const n=r[c["ID Pembelian"]];if(PurchaseRepository.findBySubmissionId("")==null && String(r[c.IdempotencyKey]||"")===""&&String(r[c.TransactionId]||"")===""&&String(r[c.PayloadFingerprint]||"")==="")return {success:true,purchaseNumber:n};throw new Error("Historical compatibility gagal");});}
function runCanonicalPurchaseP5A2ZeroInventoryCli(){return runCanonicalPurchaseP5A2Status_("ZERO_INVENTORY",function(){const p=canonicalPurchaseP5A2Fixture_("ZERO");const barang=p.items[0].kodeBarang,beforeStock=BarangRepository.getStock(barang),beforeLedger=StockLedgerRepository.sheet().getLastRow(),r=prepareCanonicalPurchaseSubmission(p),afterStock=BarangRepository.getStock(barang),afterLedger=StockLedgerRepository.sheet().getLastRow();if(afterStock!==beforeStock||afterLedger!==beforeLedger)throw new Error("Preparation mengubah inventory");return {success:true,purchaseNumber:r.purchaseNumber,barangId:barang,beforeStock:beforeStock,afterStock:afterStock,beforeLedger:beforeLedger,afterLedger:afterLedger};});}
