/** Canonical Sales S4 preparation regressions. These runners never call S3. */
function canonicalSalesS4Assert_(condition, message){ if(!condition){ throw new Error("Canonical Sales S4 gagal: " + message); } }
function canonicalSalesS4StatusKey_(name){ return "CANONICAL_SALES:S4:" + name; }
function canonicalSalesS4Run_(name, fn){
    const store=PropertiesService.getScriptProperties(), key=canonicalSalesS4StatusKey_(name);
    store.setProperty(key, JSON.stringify({status:"RUNNING"}));
    try{ const result=fn(); store.setProperty(key, JSON.stringify({status:"PASS",result:result})); return result; }
    catch(error){ store.setProperty(key, JSON.stringify({status:"FAIL",error:String(error.message||error),stack:String(error.stack||"")})); throw error; }
}
function getCanonicalSalesS4StatusCli(name){ const raw=PropertiesService.getScriptProperties().getProperty(canonicalSalesS4StatusKey_(name)); return raw?JSON.parse(raw):{status:"NOT_RUN"}; }
function canonicalSalesS4Id_(name){ return "S4-"+name+"-"+Date.now()+"-"+Math.floor(Math.random()*100000); }
function canonicalSalesS4Fixture_(name, overrides){
    const fields=overrides||{}, barang=BarangRepository.findAll().map(function(row){return String(row[COL_BARANG.ID]||"").trim();}).filter(Boolean)[0];
    const jasa=JasaRepository.findAll().map(function(row){return String(row[COL_JASA.ID]||"").trim();}).filter(Boolean)[0];
    if(!barang){ throw new Error("Fixture Barang tidak tersedia."); }
    return {
        submissionId:fields.submissionId||canonicalSalesS4Id_(name), customerId:"CUS-S4", vehicleId:"VEH-S4", mechanicId:"MKN-S4",
        paymentMethod:fields.paymentMethod||"TUNAI", amountPaid:fields.amountPaid===undefined?100000:fields.amountPaid,
        transactionDiscount:fields.transactionDiscount===undefined?0:fields.transactionDiscount, admin:"S4_TEST",
        workOrderId:fields.workOrderId||"", items:fields.items||[{jenis:"BARANG",kode:barang,qty:1,harga:10000,diskon:0,nama:"S4 Barang"}], jasaId:jasa
    };
}
function canonicalSalesS4InventorySnapshot_(){
    // S4 preparation has no inventory entry point. A direct read of the
    // stable development fixture plus ledger count gives bounded, repeatable
    // runtime evidence without scanning every MasterBarang row per scenario.
    const barangId="BRG000001";
    return {stocks:[[barangId,BarangRepository.getStock(barangId)]],ledgerRows:StockLedgerRepository.sheet().getLastRow(),wopRows:getSheet_(CONFIG.SHEET.WORK_ORDER_PART).getLastRow(),purchaseHeaders:PurchaseRepository.getHeaderSheet().getLastRow(),purchaseDetails:PurchaseRepository.getDetailSheet().getLastRow()};
}
function canonicalSalesS4AssertInventoryUnchanged_(before){
    const after=canonicalSalesS4InventorySnapshot_();
    canonicalSalesS4Assert_(JSON.stringify(after.stocks)===JSON.stringify(before.stocks),"Stok MasterBarang berubah.");
    canonicalSalesS4Assert_(after.ledgerRows===before.ledgerRows,"Stock Ledger berubah.");
    canonicalSalesS4Assert_(after.wopRows===before.wopRows,"WorkOrderPart berubah.");
    canonicalSalesS4Assert_(after.purchaseHeaders===before.purchaseHeaders&&after.purchaseDetails===before.purchaseDetails,"Purchase berubah.");
    return after;
}
function canonicalSalesS4AssertIdentity_(result, request){
    const header=PenjualanRepository.findBySalesNumber(result.salesNumber), details=PenjualanRepository.findItemsBySalesNumber(result.salesNumber), plan=result.plan;
    canonicalSalesS4Assert_(header&&header.submissionId===request.submissionId,"SubmissionId tidak tersimpan.");
    canonicalSalesS4Assert_(header.transactionId==="SALE:"+result.salesNumber+":OUT"&&header.idempotencyKey==="SALE_SUBMIT:"+request.submissionId&&header.payloadFingerprint===plan.payloadFingerprint,"Identity header tidak sesuai planner.");
    canonicalSalesS4Assert_(details.length===plan.lines.length,"Jumlah detail tidak sesuai.");
    details.forEach(function(detail,index){ canonicalSalesS4Assert_(detail.lineId===result.salesNumber+":L"+String(index+1).padStart(3,"0"),"LineId tidak deterministik."); });
    return {header:header,details:details};
}
function runCanonicalSalesS4SchemaCli(){ return canonicalSalesS4Run_("SCHEMA",function(){const preflight=getSalesCanonicalSchemaPreflight_();canonicalSalesS4Assert_(preflight.safeToApplyAppendOnly&&!preflight.header.missingAppendOnly.length&&!preflight.detail.missingAppendOnly.length,"Schema canonical belum lengkap.");return {success:true,headerColumns:preflight.header.currentHeaders.length,detailColumns:preflight.detail.currentHeaders.length};});}
function runCanonicalSalesS4NewCli(){ return canonicalSalesS4Run_("NEW",function(){const before=canonicalSalesS4InventorySnapshot_(),request=canonicalSalesS4Fixture_("NEW"),result=prepareCanonicalSalesSubmission(request);canonicalSalesS4Assert_(!result.alreadyPrepared&&result.state==="PREPARED","New preparation tidak PREPARED.");canonicalSalesS4AssertIdentity_(result,request);canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,salesNumber:result.salesNumber,submissionId:request.submissionId};});}
function runCanonicalSalesS4ResumeCli(){return canonicalSalesS4Run_("RESUME",function(){const before=canonicalSalesS4InventorySnapshot_(),request=canonicalSalesS4Fixture_("RESUME"),first=prepareCanonicalSalesSubmission(request),runningSheet=getSheet_(CONFIG.SHEET.RUNNING_NUMBER),runningBeforeRetry=JSON.stringify(runningSheet.getDataRange().getValues()),second=prepareCanonicalSalesSubmission(request),runningAfterRetry=JSON.stringify(runningSheet.getDataRange().getValues());canonicalSalesS4Assert_(first.salesNumber===second.salesNumber&&second.alreadyPrepared,"Retry tidak resume dokumen yang sama.");canonicalSalesS4Assert_(runningBeforeRetry===runningAfterRetry,"Retry mengonsumsi Sales running number kedua.");canonicalSalesS4AssertIdentity_(second,request);canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,salesNumber:first.salesNumber,runningNumberUnchanged:true};});}
function canonicalSalesS4Conflict_(name, change){return canonicalSalesS4Run_(name,function(){const before=canonicalSalesS4InventorySnapshot_(),request=canonicalSalesS4Fixture_(name),first=prepareCanonicalSalesSubmission(request),headerCount=PenjualanRepository.findAllBySubmissionId(request.submissionId).length,detailCount=PenjualanRepository.findItemsBySalesNumber(first.salesNumber).length;change(request);let conflict=false;try{prepareCanonicalSalesSubmission(request);}catch(error){conflict=String(error.message).toLowerCase().indexOf("conflict")>=0;}canonicalSalesS4Assert_(conflict,"Payload conflict tidak ditolak.");canonicalSalesS4Assert_(PenjualanRepository.findAllBySubmissionId(request.submissionId).length===headerCount&&PenjualanRepository.findItemsBySalesNumber(first.salesNumber).length===detailCount,"Conflict menambah Sales persistence untuk submission ini.");canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,salesNumber:first.salesNumber,conflict:true};});}
function runCanonicalSalesS4ConflictQtyCli(){return canonicalSalesS4Conflict_("CONFLICT_QTY",function(request){request.items[0].qty=2;});}
function runCanonicalSalesS4ConflictPaymentCli(){return canonicalSalesS4Conflict_("CONFLICT_PAYMENT",function(request){request.amountPaid=99999;});}
function runCanonicalSalesS4ConflictFulfillmentCli(){return canonicalSalesS4Conflict_("CONFLICT_FULFILLMENT",function(request){request.workOrderId="WO-S4-CONFLICT";request.items[0].fulfillmentSource="WORK_ORDER_FULFILLED";request.items[0].workOrderPartId="WOP-S4-CONFLICT";});}
function runCanonicalSalesS4DifferentSubmissionCli(){return canonicalSalesS4Run_("DIFFERENT",function(){const before=canonicalSalesS4InventorySnapshot_(),a=canonicalSalesS4Fixture_("DIFFERENT"),b=JSON.parse(JSON.stringify(a));b.submissionId=canonicalSalesS4Id_("DIFFERENT_B");const first=prepareCanonicalSalesSubmission(a),second=prepareCanonicalSalesSubmission(b);canonicalSalesS4Assert_(first.salesNumber!==second.salesNumber,"Different submission memakai nomor sama.");canonicalSalesS4AssertIdentity_(first,a);canonicalSalesS4AssertIdentity_(second,b);canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,first:first.salesNumber,second:second.salesNumber};});}
function runCanonicalSalesS4DuplicateBarangCli(){return canonicalSalesS4Run_("DUPLICATE",function(){const before=canonicalSalesS4InventorySnapshot_(),base=canonicalSalesS4Fixture_("DUPLICATE"),id=base.items[0].kode;base.items=[{jenis:"BARANG",kode:id,qty:2,harga:10000},{jenis:"BARANG",kode:id,qty:3,harga:10000}];base.amountPaid=50000;const result=prepareCanonicalSalesSubmission(base),items=PenjualanRepository.findItemsBySalesNumber(result.salesNumber);canonicalSalesS4Assert_(items.length===2&&items[0].lineId!==items[1].lineId,"Duplicate Barang tidak line-preserving.");canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,lineIds:items.map(function(item){return item.lineId;})};});}
function runCanonicalSalesS4MixedCli(){return canonicalSalesS4Run_("MIXED",function(){const before=canonicalSalesS4InventorySnapshot_(),base=canonicalSalesS4Fixture_("MIXED"),jasa=base.jasaId;if(!jasa)throw new Error("Fixture Jasa tidak tersedia.");base.items=[{jenis:"BARANG",kode:base.items[0].kode,qty:1,harga:10000},{jenis:"JASA",kode:jasa,qty:1,harga:20000}];base.amountPaid=30000;const result=prepareCanonicalSalesSubmission(base),items=PenjualanRepository.findItemsBySalesNumber(result.salesNumber);canonicalSalesS4Assert_(items.length===2&&items.map(function(i){return i.itemType;}).sort().join("|")==="BARANG|JASA","Mixed Barang/Jasa tidak tersimpan.");canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,salesNumber:result.salesNumber};});}
function runCanonicalSalesS4WopFulfilledCli(){return canonicalSalesS4Run_("WOP_FULFILLED",function(){const before=canonicalSalesS4InventorySnapshot_(),base=canonicalSalesS4Fixture_("WOP_FULFILLED",{workOrderId:"WO-S4-FULFILLED"});base.items[0].fulfillmentSource="WORK_ORDER_FULFILLED";base.items[0].workOrderPartId="WOP-S4-FULFILLED";const result=prepareCanonicalSalesSubmission(base),item=PenjualanRepository.findItemsBySalesNumber(result.salesNumber)[0];canonicalSalesS4Assert_(item.fulfillmentSource==="WORK_ORDER_FULFILLED"&&item.workOrderPartId==="WOP-S4-FULFILLED","Metadata WOP fulfilled hilang.");canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,salesNumber:result.salesNumber};});}
function runCanonicalSalesS4HistoricalCli(){return canonicalSalesS4Run_("HISTORICAL",function(){const sheet=PenjualanRepository.getHeaderSheet(),columns=PenjualanRepository.getColumnMap_(sheet),row=sheet.getDataRange().getValues().slice(1).find(function(item){return !String(item[columns.SubmissionId]||"").trim();});canonicalSalesS4Assert_(!!row,"Historical Sales tidak ditemukan.");const number=row[columns.NoTransaksi];canonicalSalesS4Assert_(!!PenjualanRepository.findBySalesNumber(number)&&PenjualanRepository.findBySubmissionId("")===null,"Historical Sales tidak kompatibel.");return {success:true,salesNumber:number};});}
function runCanonicalSalesS4PropertyRecoveryCli(){return canonicalSalesS4Run_("PROPERTY_RECOVERY",function(){const before=canonicalSalesS4InventorySnapshot_(),request=canonicalSalesS4Fixture_("PROPERTY_RECOVERY"),first=prepareCanonicalSalesSubmission(request),key=CanonicalSalesPreparationService.getPropertyKey_(request.submissionId),store=PropertiesService.getScriptProperties();store.deleteProperty(key);const resumed=prepareCanonicalSalesSubmission(request),property=JSON.parse(store.getProperty(key));canonicalSalesS4Assert_(resumed.alreadyPrepared&&property.state==="PREPARED"&&property.salesNumber===first.salesNumber,"Property missing tidak direbuild.");canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,salesNumber:first.salesNumber};});}
function runCanonicalSalesS4ReservedRecoveryCli(){return canonicalSalesS4Run_("RESERVED_RECOVERY",function(){const before=canonicalSalesS4InventorySnapshot_(),request=canonicalSalesS4Fixture_("RESERVED_RECOVERY"),salesNumber=RunningNumberService.generate(DocumentType.SALES),plan=CanonicalSalesPreparationService.createPlan_(request,salesNumber),key=CanonicalSalesPreparationService.getPropertyKey_(request.submissionId);PropertiesService.getScriptProperties().setProperty(key,JSON.stringify(CanonicalSalesPreparationService.buildProperty_(plan,"RESERVED")));const result=prepareCanonicalSalesSubmission(request);canonicalSalesS4Assert_(result.salesNumber===salesNumber,"Reserved number tidak dipakai ulang.");canonicalSalesS4AssertInventoryUnchanged_(before);return {success:true,salesNumber:salesNumber};});}
function runCanonicalSalesS4PreparedWithoutDocumentCli(){return canonicalSalesS4Run_("PREPARED_WITHOUT_DOCUMENT",function(){const request=canonicalSalesS4Fixture_("PREPARED_WITHOUT_DOCUMENT"),salesNumber=RunningNumberService.generate(DocumentType.SALES),plan=CanonicalSalesPreparationService.createPlan_(request,salesNumber),key=CanonicalSalesPreparationService.getPropertyKey_(request.submissionId);PropertiesService.getScriptProperties().setProperty(key,JSON.stringify(CanonicalSalesPreparationService.buildProperty_(plan,"PREPARED")));let blocked=false;try{prepareCanonicalSalesSubmission(request);}catch(error){blocked=String(error.message).indexOf("RECOVERY_REQUIRED")>=0;}canonicalSalesS4Assert_(blocked,"PREPARED tanpa dokumen tidak diblokir.");return {success:true,blocked:true};});}
function runCanonicalSalesS4PropertyConflictCli(){return canonicalSalesS4Run_("PROPERTY_CONFLICT",function(){const request=canonicalSalesS4Fixture_("PROPERTY_CONFLICT"),result=prepareCanonicalSalesSubmission(request),key=CanonicalSalesPreparationService.getPropertyKey_(request.submissionId),store=PropertiesService.getScriptProperties(),valid=store.getProperty(key),bad=JSON.parse(valid);bad.payloadFingerprint="DIFFERENT";store.setProperty(key,JSON.stringify(bad));let conflict=false;try{prepareCanonicalSalesSubmission(request);}catch(error){conflict=String(error.message).toLowerCase().indexOf("conflict")>=0;}store.setProperty(key,valid);canonicalSalesS4Assert_(conflict,"Property fingerprint conflict tidak ditolak.");return {success:true,salesNumber:result.salesNumber};});}
function runCanonicalSalesS4DuplicateHeaderGuardCli(){return canonicalSalesS4Run_("DUPLICATE_HEADER_GUARD",function(){let blocked=false;try{CanonicalSalesPreparationService.assertSingleExisting_([{salesNumber:"A"},{salesNumber:"B"}]);}catch(error){blocked=String(error.message).indexOf("AUDIT_ANOMALY")>=0;}canonicalSalesS4Assert_(blocked,"Duplicate canonical header anomaly tidak diblokir.");return {success:true,blocked:true};});}
function runCanonicalSalesS4ParallelWorkerCli(submissionId, quantity){const base=canonicalSalesS4Fixture_("PARALLEL",{submissionId:String(submissionId),amountPaid:100000});base.items[0].qty=Number(quantity||1);base.amountPaid=Number(quantity||1)*10000;return prepareCanonicalSalesSubmission(base);}
function inspectCanonicalSalesS4ParallelCli(submissionId){const headers=PenjualanRepository.findAllBySubmissionId(submissionId);return {success:true,submissionId:submissionId,headerCount:headers.length,salesNumbers:headers.map(function(h){return h.salesNumber;}),detailCount:headers.length?PenjualanRepository.findItemsBySalesNumber(headers[0].salesNumber).length:0,property:CanonicalSalesPreparationService.readProperty_(CanonicalSalesPreparationService.getPropertyKey_(submissionId))};}
