/** S6.4T true-concurrency runners. Test-only fixture orchestration; no production-service changes. */
const CANONICAL_WO_S64T={actor:"S6.4_TEST",barangOne:"BRG000166",barangTwo:"BRG000168",prefix:"CANONICAL_WO_SETTLEMENT:S6.4T:"};

function s64tText_(value){return String(value===undefined||value===null?"":value).trim();}
function s64tAssert_(condition,message){if(!condition)throw new Error(message);}
function s64tScenarioKey_(scenario){return CANONICAL_WO_S64T.prefix+"SCENARIO:"+s64tText_(scenario);}
function s64tWorkerKey_(scenario,worker){return CANONICAL_WO_S64T.prefix+"WORKER:"+s64tText_(scenario)+":"+s64tText_(worker);}
function s64tRead_(key){const raw=PropertiesService.getScriptProperties().getProperty(key);return raw?JSON.parse(raw):null;}
function s64tWrite_(key,value){PropertiesService.getScriptProperties().setProperty(key,JSON.stringify(value));return value;}
function s64tStock_(barangId){return Number(BarangRepository.getStock(barangId));}
function s64tFreshStock_(barangId){const ss=SpreadsheetApp.openById(SpreadsheetApp.getActiveSpreadsheet().getId()),sh=ss.getSheetByName(CONFIG.SHEET.BARANG),rows=sh.getDataRange().getValues().slice(1),row=rows.find(function(item){return s64tText_(item[COL_BARANG.ID])===s64tText_(barangId);});return row?Number(row[COL_BARANG.STOK]):null;}
function s64tGuard_(){const guards={brg000001:s64tStock_("BRG000001"),brg000097:s64tStock_("BRG000097"),brg000166:s64tStock_(CANONICAL_WO_S64T.barangOne),brg000167:s64tStock_("BRG000167"),brg000168:s64tStock_(CANONICAL_WO_S64T.barangTwo)};s64tAssert_(guards.brg000001===66&&guards.brg000097===30&&guards.brg000166===20&&guards.brg000167===8&&guards.brg000168===20,"Guard S6.4T tidak sesuai: "+JSON.stringify(guards));return guards;}
function s64tItems_(barangId,qty){return [{jenis:"BARANG",kode:barangId,qty:Number(qty),harga:1}];}
function s64tBuildInput_(workOrderId,submissionId,barangId,qty,discountValue){const items=s64tItems_(barangId,qty),plan=planCanonicalWorkOrderSettlement({workOrderId:workOrderId,submissionId:submissionId,directSaleItems:items,discountType:"NOMINAL",discountValue:Number(discountValue)||0,paymentIntent:{paymentMethod:"TUNAI",amountPaid:0,admin:CANONICAL_WO_S64T.actor}});s64tAssert_(plan.eligible,"Planner S6.4T menolak fixture: "+plan.errors.join(" | "));return {workOrderId:workOrderId,submissionId:submissionId,directSaleItems:items,discountType:"NOMINAL",discountValue:Number(discountValue)||0,paymentMethod:"TUNAI",amountPaid:Number(plan.subtotal)-Number(discountValue||0),admin:CANONICAL_WO_S64T.actor};}
function s64tCreateWo_(marker){return s64FactoryCreateWo_("S64T_"+marker,false,"").workOrderId;}
function s64tConfig_(scenario){const config=s64tRead_(s64tScenarioKey_(scenario));s64tAssert_(!!config,"Fixture S6.4T belum disiapkan: "+scenario);return config;}
function getCanonicalWorkOrderSettlementS64TScenarioStatusCli(scenario){return s64tRead_(s64tScenarioKey_(s64tText_(scenario).toUpperCase()))||{scenario:s64tText_(scenario).toUpperCase(),state:"NOT_FOUND"};}
function auditCanonicalWorkOrderSettlementS64TSetupCli(scenario){const id=s64tText_(scenario).toUpperCase(),markers=id==="D"?["S64T_D_DIFFERENT_WO_A","S64T_D_DIFFERENT_WO_B"]:["S64T_"+id],rows=markers.map(function(marker){const matches=s64FactoryFindWo_(marker);return {marker:marker,count:matches.length,workOrderIdsJson:JSON.stringify(matches.map(function(row){return s64tText_(row[COL_WORK_ORDER.ID]);})),statusJson:JSON.stringify(matches.map(function(row){return s64tText_(row[COL_WORK_ORDER.STATUS]);}))};});return {scenario:id,configExists:!!s64tRead_(s64tScenarioKey_(id)),setupJson:JSON.stringify(rows),brg000166:s64tStock_(CANONICAL_WO_S64T.barangOne),brg000168:s64tStock_(CANONICAL_WO_S64T.barangTwo),brg000001:s64tStock_("BRG000001"),brg000097:s64tStock_("BRG000097")};}

function prepareCanonicalWorkOrderSettlementS64TScenarioCli(scenario){const id=s64tText_(scenario).toUpperCase(),lock=LockService.getScriptLock();s64tAssert_(["A","B","C","D"].indexOf(id)>=0,"Scenario S6.4T tidak dikenal.");lock.waitLock(30000);try{const existing=s64tRead_(s64tScenarioKey_(id));if(existing)return existing;const guards=s64tGuard_();let config;
  if(id==="A"){const wo=s64tCreateWo_("A_SAME_PAYLOAD");config={scenario:id,workOrderIds:[wo],barangId:CANONICAL_WO_S64T.barangOne,baseline:guards.brg000166,workers:[{workerId:"A1",workOrderId:wo,submissionId:"S64T-A-UI-1",qty:1,discountValue:0},{workerId:"A2",workOrderId:wo,submissionId:"S64T-A-UI-2",qty:1,discountValue:0}]};}
  if(id==="B"){const wo=s64tCreateWo_("B_CHANGED_PAYLOAD");config={scenario:id,workOrderIds:[wo],barangId:CANONICAL_WO_S64T.barangOne,baseline:guards.brg000166,workers:[{workerId:"B1",workOrderId:wo,submissionId:"S64T-B-UI-1",qty:1,discountValue:0},{workerId:"B2",workOrderId:wo,submissionId:"S64T-B-UI-2",qty:2,discountValue:0}]};}
  if(id==="C"){const wo=s64tCreateWo_("C_PREPARED_TWO_WORKERS"),submissionId="S64T-C-PREPARED-001",input=s64tBuildInput_(wo,submissionId,CANONICAL_WO_S64T.barangOne,1,0),prepared=prepareCanonicalWorkOrderSettlement({workOrderId:wo,submissionId:submissionId,directSaleItems:input.directSaleItems,discountType:input.discountType,discountValue:input.discountValue,paymentIntent:{paymentMethod:"TUNAI",amountPaid:input.amountPaid,admin:CANONICAL_WO_S64T.actor}});s64tAssert_(prepared.state==="PREPARED"&&!!prepared.salesNumber,"Fixture prepared S6.4T tidak valid.");config={scenario:id,workOrderIds:[wo],barangId:CANONICAL_WO_S64T.barangOne,baseline:guards.brg000166,preparedSalesNumber:prepared.salesNumber,workers:[{workerId:"C1",workOrderId:wo,submissionId:submissionId,qty:1,discountValue:0},{workerId:"C2",workOrderId:wo,submissionId:submissionId,qty:1,discountValue:0}]};}
  if(id==="D"){const woA=s64tCreateWo_("D_DIFFERENT_WO_A"),woB=s64tCreateWo_("D_DIFFERENT_WO_B");config={scenario:id,workOrderIds:[woA,woB],barangId:CANONICAL_WO_S64T.barangTwo,baseline:guards.brg000168,workers:[{workerId:"D1",workOrderId:woA,submissionId:"S64T-D-UI-1",qty:1,discountValue:0},{workerId:"D2",workOrderId:woB,submissionId:"S64T-D-UI-2",qty:2,discountValue:0}]};}
  config.state="PREPARED";config.createdAt=new Date().toISOString();s64tWrite_(s64tScenarioKey_(id),config);return config;
}finally{lock.releaseLock();}}

function runCanonicalWorkOrderSettlementS64TWorkerCli(scenario,workerId){const id=s64tText_(scenario).toUpperCase(),worker=s64tText_(workerId),config=s64tConfig_(id),request=config.workers.filter(function(item){return item.workerId===worker;})[0];s64tAssert_(!!request,"Worker S6.4T tidak ditemukan: "+worker);const key=s64tWorkerKey_(id,worker),startedAt=new Date().toISOString();s64tWrite_(key,{scenario:id,workerId:worker,state:"RUNNING",startedAt:startedAt,finishedAt:"",workOrderId:request.workOrderId,submissionId:request.submissionId,salesNumber:"",error:""});try{const input=s64tBuildInput_(request.workOrderId,request.submissionId,config.barangId,request.qty,request.discountValue),result=settleCanonicalWorkOrder(input),status={scenario:id,workerId:worker,state:"PASS",startedAt:startedAt,finishedAt:new Date().toISOString(),workOrderId:request.workOrderId,submissionId:request.submissionId,salesNumber:s64tText_(result.salesNumber),salesStatus:s64tText_(result.status),settlementStatus:s64tText_(result.settlementStatus),alreadyPrepared:!!result.alreadyPrepared,alreadyRecorded:!!result.alreadyRecorded,alreadySettled:!!result.alreadySettled,error:""};s64tWrite_(key,status);return status;}catch(error){const message=String(error.message||error),status={scenario:id,workerId:worker,state:message.indexOf("SETTLEMENT_CONFLICT")>=0?"CONFLICT":"FAIL",startedAt:startedAt,finishedAt:new Date().toISOString(),workOrderId:request.workOrderId,submissionId:request.submissionId,salesNumber:"",salesStatus:"",settlementStatus:"",alreadyPrepared:false,alreadyRecorded:false,alreadySettled:false,error:message};s64tWrite_(key,status);return status;}}

function getCanonicalWorkOrderSettlementS64TWorkerStatusCli(scenario,workerId){return s64tRead_(s64tWorkerKey_(s64tText_(scenario).toUpperCase(),workerId))||{scenario:s64tText_(scenario).toUpperCase(),workerId:s64tText_(workerId),state:"NOT_FOUND"};}
function s64tDirectLines_(salesNumber){return PenjualanRepository.findItemsBySalesNumber(salesNumber).filter(function(line){return s64tText_(line.itemType)==="BARANG"&&s64tText_(line.fulfillmentSource)==="DIRECT_SALE"&&s64tText_(line.sourceDocumentType)==="DIRECT_SALE";});}
function s64tLedger_(line){const rows=StockLedgerRepository.findByReferensiFresh(line.lineId);return rows.map(function(row){return {ledgerId:s64tText_(row[COL_STOK.ID]),reference:s64tText_(row[COL_STOK.REFERENSI]),qtyOut:Number(row[COL_STOK.QTYKELUAR]),stokAwal:Number(row[COL_STOK.STOKAWAL]),stokAkhir:Number(row[COL_STOK.STOKAKHIR]),movementType:s64tText_(row[COL_STOK.JENISMUTASI])};});}
function s64tSalesEvidence_(workOrderId){const sales=PenjualanRepository.findSettlementSalesByWorkOrder(workOrderId);return sales.map(function(header){const lines=s64tDirectLines_(header.salesNumber),ledgers=lines.reduce(function(all,line){return all.concat(s64tLedger_(line));},[]);return {salesNumber:s64tText_(header.salesNumber),status:s64tText_(header.status),paymentMethod:s64tText_(header.paymentMethod),amountPaid:Number(header.amountPaid),grandTotal:Number(header.grandTotal),change:Number(header.change),lineCount:lines.length,lines:lines,ledgers:ledgers};});}
function auditCanonicalWorkOrderSettlementS64TScenarioCli(scenario){
  const id=s64tText_(scenario).toUpperCase(),config=s64tConfig_(id);
  const workers=config.workers.map(function(item){return getCanonicalWorkOrderSettlementS64TWorkerStatusCli(id,item.workerId);});
  const salesByWo=config.workOrderIds.map(function(wo){return {workOrderId:wo,sales:s64tSalesEvidence_(wo),metadata:WorkOrderRepository.getSettlementMetadata(wo)};});
  const totalSales=salesByWo.reduce(function(total,item){return total+item.sales.length;},0);
  const allLedgers=salesByWo.reduce(function(all,item){return all.concat(item.sales.reduce(function(next,sale){return next.concat(sale.ledgers);},[]));},[]);
  const qtyOut=allLedgers.reduce(function(total,row){return total+row.qtyOut;},0),stock=s64tStock_(config.barangId),fresh=s64tFreshStock_(config.barangId);
  s64tAssert_(workers.every(function(item){return item.state!=="RUNNING"&&item.state!=="NOT_FOUND";}),"Worker S6.4T belum terminal.");
  s64tAssert_(fresh===stock,"Fresh stock S6.4T tidak sama.");
  if(id==="A"||id==="C")s64tAssert_(totalSales===1&&allLedgers.length===1&&qtyOut===1&&stock===config.baseline-1&&workers.every(function(item){return item.state==="PASS";}),"Same settlement S6.4T tidak idempoten.");
  if(id==="B"){const conflicts=workers.filter(function(item){return item.state==="CONFLICT";}),passes=workers.filter(function(item){return item.state==="PASS";});s64tAssert_(passes.length===1&&conflicts.length===1&&totalSales===1&&allLedgers.length===1&&(qtyOut===1||qtyOut===2)&&stock===config.baseline-qtyOut,"Changed payload S6.4T tidak conflict aman.");}
  if(id==="D"){s64tAssert_(workers.every(function(item){return item.state==="PASS";})&&totalSales===2&&allLedgers.length===2&&qtyOut===3&&stock===config.baseline-3,"Different Work Order S6.4T kehilangan stock update.");const ordered=allLedgers.slice().sort(function(a,b){return b.stokAwal-a.stokAwal;});s64tAssert_(ordered.length===2&&ordered[0].stokAkhir===ordered[1].stokAwal,"Stock chain S6.4T tidak kontinu.");}
  salesByWo.forEach(function(item){const sale=item.sales[0];s64tAssert_(item.sales.length===1,"Sales Work Order S6.4T tidak unik: "+item.workOrderId);s64tAssert_(sale.status===SalesStatus.LUNAS&&sale.paymentMethod==="TUNAI"&&sale.amountPaid>=sale.grandTotal&&sale.change===sale.amountPaid-sale.grandTotal&&s64tText_(item.metadata.settlementStatus)==="SETTLED"&&s64tText_(item.metadata.settlementSalesNumber)===sale.salesNumber,"Finalisasi/payment S6.4T tidak valid.");});
  return {success:true,scenario:id,workerStatesJson:JSON.stringify(workers),salesJson:JSON.stringify(salesByWo.map(function(item){return {workOrderId:item.workOrderId,salesNumber:item.sales[0].salesNumber,lineIds:item.sales[0].lines.map(function(line){return line.lineId;}),ledgerIds:item.sales[0].ledgers.map(function(row){return row.ledgerId;})};})),ledgerJson:JSON.stringify(allLedgers),salesCount:totalSales,ledgerCount:allLedgers.length,qtyOut:qtyOut,stock:stock,freshStock:fresh,barangId:config.barangId};
}

function cleanupCanonicalWorkOrderSettlementS64TScenarioCli(scenario){const id=s64tText_(scenario).toUpperCase(),config=s64tConfig_(id),audit=auditCanonicalWorkOrderSettlementS64TScenarioCli(id),sales=config.workOrderIds.reduce(function(all,wo){return all.concat(s64tSalesEvidence_(wo));},[]),cleanup=[];sales.forEach(function(sale){sale.lines.forEach(function(line){const reference="S64T_TEST_CLEANUP:"+id+":"+sale.salesNumber+":"+line.lineId,existing=StockLedgerRepository.findByReferensiFresh(reference);s64tAssert_(existing.length<=1,"Cleanup S6.4T duplicate: "+reference);if(!existing.length)InventoryService.moveStock({kodeBarang:line.itemId,movementType:MovementType.PURCHASE,qty:Number(line.quantity),reference:reference,performedBy:CANONICAL_WO_S64T.actor,note:"S6.4T true-concurrency fixture cleanup; non-production"});const row=StockLedgerRepository.findByReferensiFresh(reference);s64tAssert_(row.length===1&&Number(row[0][COL_STOK.QTYMASUK])===Number(line.quantity),"Cleanup S6.4T tidak valid: "+reference);cleanup.push({reference:reference,ledgerId:s64tText_(row[0][COL_STOK.ID]),qty:Number(row[0][COL_STOK.QTYMASUK])});});});const after=s64tStock_(config.barangId),fresh=s64tFreshStock_(config.barangId);s64tAssert_(after===config.baseline&&fresh===config.baseline,"Cleanup S6.4T tidak memulihkan baseline.");return {success:true,scenario:id,barangId:config.barangId,cleanupJson:JSON.stringify(cleanup),cleanupCount:cleanup.length,qtyIn:cleanup.reduce(function(total,item){return total+item.qty;},0),stockAfter:after,freshStockAfter:fresh,auditQtyOut:audit.qtyOut};}
function auditCanonicalWorkOrderSettlementS64TRawCli(scenario){const id=s64tText_(scenario).toUpperCase(),config=s64tConfig_(id),workers=config.workers.map(function(item){return getCanonicalWorkOrderSettlementS64TWorkerStatusCli(id,item.workerId);}),sales=config.workOrderIds.map(function(workOrderId){return {workOrderId:workOrderId,sales:s64tSalesEvidence_(workOrderId),metadata:WorkOrderRepository.getSettlementMetadata(workOrderId)};}),ledgers=sales.reduce(function(all,item){return all.concat(item.sales.reduce(function(next,sale){return next.concat(sale.ledgers);},[]));},[]);return {success:true,scenario:id,barangId:config.barangId,workersJson:JSON.stringify(workers),salesJson:JSON.stringify(sales.map(function(item){return {workOrderId:item.workOrderId,salesNumbers:item.sales.map(function(sale){return sale.salesNumber;}),settlementStatus:s64tText_(item.metadata&&item.metadata.settlementStatus),settlementSalesNumber:s64tText_(item.metadata&&item.metadata.settlementSalesNumber)};})),ledgersJson:JSON.stringify(ledgers),normalStock:s64tStock_(config.barangId),freshStock:s64tFreshStock_(config.barangId)};}

function auditCanonicalWorkOrderSettlementS64TFinalGuardsCli(){const guards=s64tGuard_(),active=getCanonicalWorkOrderSettlementS64ActiveRunCli();s64tAssert_(active.state==="IDLE","S6.4 ACTIVE_RUN belum IDLE.");["A","B","C","D"].forEach(function(id){const config=s64tConfig_(id);config.workers.forEach(function(worker){const state=getCanonicalWorkOrderSettlementS64TWorkerStatusCli(id,worker.workerId);s64tAssert_(state.state!=="RUNNING"&&state.state!=="NOT_FOUND","Worker akhir tidak terminal: "+id+":"+worker.workerId);});});return {success:true,brg000001:guards.brg000001,brg000097:guards.brg000097,brg000166:guards.brg000166,brg000167:guards.brg000167,brg000168:guards.brg000168,activeRun:active.state};}
