/** Pure S6.2 settlement planner regressions. */
function canonicalWoSettlementAssert_(value,message){if(!value)throw new Error("Canonical WO Settlement S6.2 gagal: "+message);}
function canonicalWoSettlementRow_(size,fields){const row=Array(size).fill("");Object.keys(fields).forEach(function(index){row[Number(index)]=fields[index];});return row;}
function canonicalWoSettlementFixtures_(){
  const wo=canonicalWoSettlementRow_(COL_WORK_ORDER.TOTAL,{[COL_WORK_ORDER.ID]:"WO-S6-001",[COL_WORK_ORDER.STATUS]:WorkOrderStatus.SELESAI});
  const jasaDone=canonicalWoSettlementRow_(17,{[COL_WO_JASA.ID]:"WOJ-S6-DONE",[COL_WO_JASA.WORK_ORDER_ID]:"WO-S6-001",[COL_WO_JASA.JASA_ID]:"JSA-S6",[COL_WO_JASA.NAMA_JASA]:"Service Snapshot",[COL_WO_JASA.QTY]:1,[COL_WO_JASA.HARGA]:70000,[COL_WO_JASA.DISKON]:5000,[COL_WO_JASA.SUBTOTAL]:65000,[COL_WO_JASA.STATUS]:WorkOrderJasaStatus.DONE});
  const jasaCancel=canonicalWoSettlementRow_(17,{[COL_WO_JASA.ID]:"WOJ-S6-CANCEL",[COL_WO_JASA.WORK_ORDER_ID]:"WO-S6-001",[COL_WO_JASA.JASA_ID]:"JSA-C",[COL_WO_JASA.QTY]:1,[COL_WO_JASA.HARGA]:10000,[COL_WO_JASA.SUBTOTAL]:10000,[COL_WO_JASA.STATUS]:WorkOrderJasaStatus.CANCEL});
  const partDone=canonicalWoSettlementRow_(COL_WORK_ORDER_PART.TOTAL+1,{[COL_WORK_ORDER_PART.ID]:"WOP-S6-DONE",[COL_WORK_ORDER_PART.WORK_ORDER_ID]:"WO-S6-001",[COL_WORK_ORDER_PART.BARANG_ID]:"BRG-S6-OLI",[COL_WORK_ORDER_PART.NAMA_BARANG_SNAPSHOT]:"Oli Snapshot",[COL_WORK_ORDER_PART.QTY]:2,[COL_WORK_ORDER_PART.HARGA]:40000,[COL_WORK_ORDER_PART.DISKON]:0,[COL_WORK_ORDER_PART.TOTAL]:80000,[COL_WORK_ORDER_PART.STATUS]:WorkOrderPartStatus.DONE});
  const partCancel=canonicalWoSettlementRow_(COL_WORK_ORDER_PART.TOTAL+1,{[COL_WORK_ORDER_PART.ID]:"WOP-S6-CANCEL",[COL_WORK_ORDER_PART.WORK_ORDER_ID]:"WO-S6-001",[COL_WORK_ORDER_PART.BARANG_ID]:"BRG-S6-X",[COL_WORK_ORDER_PART.QTY]:1,[COL_WORK_ORDER_PART.HARGA]:10000,[COL_WORK_ORDER_PART.TOTAL]:10000,[COL_WORK_ORDER_PART.STATUS]:WorkOrderPartStatus.CANCEL});
  const ledger=canonicalWoSettlementRow_(14,{[COL_STOK.ID]:"STK-S6-OUT",[COL_STOK.BARANG_ID]:"BRG-S6-OLI",[COL_STOK.JENISMUTASI]:"SERVICE",[COL_STOK.REFERENSI]:"WOP-S6-DONE",[COL_STOK.QTYKELUAR]:2,[COL_STOK.STOKAWAL]:10,[COL_STOK.STOKAKHIR]:8});
  const barang=canonicalWoSettlementRow_(COL_BARANG.TOTAL,{[COL_BARANG.ID]:"BRG-S6-BUSI",[COL_BARANG.HARGAJUAL]:25000}); const jasa=canonicalWoSettlementRow_(COL_JASA.TOTAL,{[COL_JASA.ID]:"JSA-S6-DIRECT",[COL_JASA.HARGA]:30000});
  return {wo:wo,jasa:[jasaDone,jasaCancel],parts:[partDone,partCancel],ledger:{"WOP-S6-DONE":[ledger]},barang:barang,jasaMaster:jasa};
}
function canonicalWoSettlementOptions_(fixture){return {findWorkOrder:function(){return fixture.wo;},findWorkOrderJasa:function(){return fixture.jasa;},findWorkOrderPart:function(){return fixture.parts;},findLedgerByReference:function(id){return fixture.ledger[id]||[];},findBarang:function(id){return id==="BRG-S6-BUSI"?fixture.barang:null;},findJasa:function(id){return id==="JSA-S6-DIRECT"?fixture.jasaMaster:null;}};}
function canonicalWoSettlementInput_(direct){return {workOrderId:"WO-S6-001",submissionId:"UI-S6-001",directSaleItems:direct||[],discountType:"NOMINAL",discountValue:1000,paymentIntent:{paymentMethod:"TUNAI",amountPaid:999999}};}
function canonicalWoSettlementSnapshot_(){const names=[CONFIG.SHEET.WORK_ORDER,CONFIG.SHEET.WORK_ORDER_JASA,CONFIG.SHEET.WORK_ORDER_PART,CONFIG.SHEET.PENJUALAN,CONFIG.SHEET.DETAIL_PENJUALAN,CONFIG.SHEET.BARANG,CONFIG.SHEET.STOK,CONFIG.SHEET.RUNNING_NUMBER],properties=PropertiesService.getScriptProperties().getProperties();return {sheets:names.map(function(name){const sheet=getSheet_(name);return [name,JSON.stringify(sheet.getDataRange().getValues())];}),properties:Object.keys(properties).sort().map(function(key){return [key,properties[key]];}),stock:BarangRepository.getStock("BRG000001")};}
function runCanonicalWorkOrderSettlementPlannerRegressionCli(){
  const before=canonicalWoSettlementSnapshot_(),fixture=canonicalWoSettlementFixtures_(),options=canonicalWoSettlementOptions_(fixture),mixed=planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_([{jenis:"BARANG",kode:"BRG-S6-BUSI",qty:1,harga:1},{jenis:"JASA",kode:"JSA-S6-DIRECT",qty:1,harga:1}]),options);
  canonicalWoSettlementAssert_(mixed.eligible&&mixed.settlementIdentity==="WO_SETTLEMENT:WO-S6-001","eligible/identity tidak sesuai.");
  canonicalWoSettlementAssert_(mixed.woJasaLines.length===1&&mixed.woJasaLines[0].unitPriceIntent===70000&&mixed.woJasaLines[0].lineSubtotal===65000,"Jasa DONE snapshot tidak dipertahankan atau CANCEL tidak dikecualikan.");
  canonicalWoSettlementAssert_(mixed.woPartLines.length===1&&mixed.woPartLines[0].quantity===2&&mixed.woPartLines[0].requiresInventoryMovement===false,"WOP DONE valid tidak menjadi fulfilled non-inventory.");
  canonicalWoSettlementAssert_(mixed.inventoryLines.length===1&&mixed.inventoryLines[0].itemId==="BRG-S6-BUSI"&&mixed.inventoryLines[0].unitPriceIntent===25000&&mixed.nonInventoryLines.length===3,"Mixed WO/direct inventory classification tidak sesuai.");
  canonicalWoSettlementAssert_(mixed.subtotal===200000,"Subtotal snapshot WO/direct tidak sesuai.");
  const repeat=planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_([{jenis:"JASA",kode:"JSA-S6-DIRECT",qty:1},{jenis:"BARANG",kode:"BRG-S6-BUSI",qty:1}]),options);
  canonicalWoSettlementAssert_(mixed.settlementFingerprint===repeat.settlementFingerprint&&compareWorkOrderSettlement(mixed,repeat)==="SAME_SETTLEMENT","Fingerprint/comparator same tidak deterministik.");
  const changed=planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_([{jenis:"BARANG",kode:"BRG-S6-BUSI",qty:2}]),options);canonicalWoSettlementAssert_(compareWorkOrderSettlement(mixed,changed)==="SETTLEMENT_CONFLICT","Changed payload tidak conflict.");
  fixture.wo[COL_WORK_ORDER.STATUS]=WorkOrderStatus.QC;canonicalWoSettlementAssert_(!planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_(),options).eligible,"Non-SELESAI tidak ditolak.");fixture.wo[COL_WORK_ORDER.STATUS]=WorkOrderStatus.DIBATALKAN;canonicalWoSettlementAssert_(!planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_(),options).eligible,"DIBATALKAN tidak ditolak.");fixture.wo[COL_WORK_ORDER.STATUS]=WorkOrderStatus.SELESAI;
  fixture.jasa[0][COL_WO_JASA.STATUS]=WorkOrderJasaStatus.PROGRESS;canonicalWoSettlementAssert_(!planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_(),options).eligible,"Jasa unresolved tidak ditolak.");fixture.jasa[0][COL_WO_JASA.STATUS]=WorkOrderJasaStatus.DONE;
  fixture.ledger["WOP-S6-DONE"]=[];canonicalWoSettlementAssert_(!planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_(),options).eligible,"WOP missing OUT tidak ditolak.");fixture.ledger["WOP-S6-DONE"]=[canonicalWoSettlementFixtures_().ledger["WOP-S6-DONE"][0]];fixture.ledger["WOP-S6-DONE"][0][COL_STOK.QTYKELUAR]=1;canonicalWoSettlementAssert_(!planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_(),options).eligible,"WOP qty mismatch tidak ditolak.");fixture.ledger["WOP-S6-DONE"][0][COL_STOK.QTYKELUAR]=2;fixture.ledger["WOP-S6-DONE"].push(canonicalWoSettlementRow_(14,{[COL_STOK.JENISMUTASI]:"REVERSAL",[COL_STOK.REFERENSI]:"WOP-S6-DONE",[COL_STOK.QTYMASUK]:2}));canonicalWoSettlementAssert_(!planCanonicalWorkOrderSettlement(canonicalWoSettlementInput_(),options).eligible,"WOP reversal tidak ditolak.");
  const after=canonicalWoSettlementSnapshot_();canonicalWoSettlementAssert_(JSON.stringify(before.sheets)===JSON.stringify(after.sheets),"Planner mengubah isi sheet runtime.");canonicalWoSettlementAssert_(before.stock===after.stock,"Planner mengubah stok MasterBarang.");canonicalWoSettlementAssert_(JSON.stringify(before.properties)===JSON.stringify(after.properties),"Planner mengubah ScriptProperties.");return {success:true,test:"CANONICAL_WO_SETTLEMENT_S6_2",message:"PASS"};
}
