/** Read-only S6.3B observability helpers. */
function canonicalWoS63Text_(value){return String(value===undefined||value===null?"":value).trim();}
function canonicalWoS63StatusKey_(runId){return "CANONICAL_WO_SETTLEMENT:S6.3:RUN:"+canonicalWoS63Text_(runId);}
function getCanonicalWorkOrderSettlementS63RunStatusCli(runId){const raw=PropertiesService.getScriptProperties().getProperty(canonicalWoS63StatusKey_(runId));return raw?JSON.parse(raw):{found:false,runId:canonicalWoS63Text_(runId)};}
function getCanonicalWorkOrderSettlementS63ActiveRunCli(){const raw=PropertiesService.getScriptProperties().getProperty("CANONICAL_WO_SETTLEMENT:S6.3:ACTIVE_RUN");return raw?JSON.parse(raw):{state:"IDLE"};}
function getCanonicalWorkOrderSettlementReservationCli(workOrderId){const id=canonicalWoS63Text_(workOrderId),raw=PropertiesService.getScriptProperties().getProperty("CANONICAL_WO_SETTLEMENT:PREPARE:"+id),value=raw?JSON.parse(raw):{};return {workOrderId:id,propertyExists:!!raw,state:canonicalWoS63Text_(value.state),settlementIdentity:canonicalWoS63Text_(value.settlementIdentity),settlementFingerprint:canonicalWoS63Text_(value.settlementFingerprint),salesNumber:canonicalWoS63Text_(value.salesNumber),createdAt:canonicalWoS63Text_(value.createdAt),updatedAt:canonicalWoS63Text_(value.updatedAt)};}
function findCanonicalWorkOrderSettlementSafeCandidatesCli(){const sh=WorkOrderRepository.sheet(),h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],id=h.indexOf("ID"),status=h.indexOf("Status"),name=h.indexOf("Nama Pelanggan"),vehicle=h.indexOf("No Polisi");return sh.getDataRange().getValues().slice(1).map(function(row){const workOrderId=canonicalWoS63Text_(row[id]),meta=workOrderId?WorkOrderRepository.getSettlementMetadata(workOrderId):null,res=workOrderId?getCanonicalWorkOrderSettlementReservationCli(workOrderId):null,sales=workOrderId?PenjualanRepository.findSettlementSalesByWorkOrder(workOrderId):[],jasa=workOrderId?WorkOrderJasaRepository.findByWorkOrderId(workOrderId):[],part=workOrderId?WorkOrderPartRepository.findByWorkOrderId(workOrderId):[],plan=workOrderId?planCanonicalWorkOrderSettlement({workOrderId:workOrderId,directSaleItems:[{jenis:"BARANG",kode:"BRG000097",qty:1}]}):null;return {workOrderId:workOrderId,status:canonicalWoS63Text_(row[status]),customer:canonicalWoS63Text_(row[name]),vehicle:canonicalWoS63Text_(row[vehicle]),jasaCount:jasa.length,partCount:part.length,salesCount:sales.length,settlementSalesNumber:meta&&meta.settlementSalesNumber||"",settlementIdentity:meta&&meta.settlementIdentity||"",reservationExists:res&&res.propertyExists||false,eligible:plan&&plan.eligible||false,errors:plan&&plan.errors||[]};}).filter(function(x){return x.status===WorkOrderStatus.SELESAI&&!x.salesCount&&!x.settlementSalesNumber&&!x.settlementIdentity&&!x.reservationExists&&x.eligible;}).slice(0,10);}
function listCanonicalWorkOrderSettlementCandidateBatchCli(){const sh=WorkOrderRepository.sheet(),h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],id=h.indexOf("ID"),status=h.indexOf("Status"),name=h.indexOf("Nama Pelanggan"),vehicle=h.indexOf("No Polisi"),ss=h.indexOf("SettlementStatus"),sn=h.indexOf("SettlementSalesNumber"),si=h.indexOf("SettlementIdentity");return sh.getDataRange().getValues().slice(1).filter(function(r){return canonicalWoS63Text_(r[status])===WorkOrderStatus.SELESAI&&!canonicalWoS63Text_(r[sn])&&!canonicalWoS63Text_(r[si])&&["WO2608140015","WO2608200012"].indexOf(canonicalWoS63Text_(r[id]))<0;}).slice(0,10).map(function(r){return {workOrderId:canonicalWoS63Text_(r[id]),status:canonicalWoS63Text_(r[status]),customer:canonicalWoS63Text_(r[name]),vehicle:canonicalWoS63Text_(r[vehicle]),settlementStatus:canonicalWoS63Text_(r[ss]),settlementSalesNumber:canonicalWoS63Text_(r[sn]),settlementIdentity:canonicalWoS63Text_(r[si])};});}
function auditCanonicalWorkOrderSettlementCandidateCli(workOrderId){const id=canonicalWoS63Text_(workOrderId),meta=WorkOrderRepository.getSettlementMetadata(id),sales=PenjualanRepository.findSettlementSalesByWorkOrder(id),res=getCanonicalWorkOrderSettlementReservationCli(id),plan=planCanonicalWorkOrderSettlement({workOrderId:id,directSaleItems:[{jenis:"BARANG",kode:"BRG000097",qty:1}]}),jasa=WorkOrderJasaRepository.findByWorkOrderId(id),part=WorkOrderPartRepository.findByWorkOrderId(id);let classification="SAFE",reason="eligible";if(sales.length)classification="UNSAFE_EXISTING_SALES",reason="Sales exists";else if(meta&&(meta.settlementSalesNumber||meta.settlementIdentity))classification="UNSAFE_SETTLEMENT_METADATA",reason="metadata exists";else if(res.propertyExists)classification="UNSAFE_RESERVATION",reason="reservation exists";else if(!plan.eligible)classification="PLANNER_REJECTED",reason=plan.errors.join(" | ");return {workOrderId:id,classification:classification,reason:reason,jasaCount:jasa.length,partCount:part.length,jasaStatusesJson:JSON.stringify(jasa.map(function(r){return r[COL_WO_JASA.STATUS];})),partStatusesJson:JSON.stringify(part.map(function(r){return r[COL_WORK_ORDER_PART.STATUS];})),salesCount:sales.length,reservationExists:res.propertyExists,eligible:plan.eligible,errorsJson:JSON.stringify(plan.errors)};}
function canonicalWoS63ScanKey_(id){return "CANONICAL_WO_SETTLEMENT:S6.3:SCAN:"+id;}function getCanonicalWorkOrderSettlementS63ScanStatusCli(id){const raw=PropertiesService.getScriptProperties().getProperty(canonicalWoS63ScanKey_(id));return raw?JSON.parse(raw):{runId:id,state:"NOT_FOUND"};}
function runCanonicalWorkOrderSettlementCandidateScanCli(runId,startRow,limit){const store=PropertiesService.getScriptProperties(),key=canonicalWoS63ScanKey_(runId),sh=WorkOrderRepository.sheet(),h=sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0],id=h.indexOf("ID"),status=h.indexOf("Status"),si=h.indexOf("SettlementIdentity"),sn=h.indexOf("SettlementSalesNumber"),first=Math.max(2,Number(startRow)||2),size=Math.min(20,Math.max(1,Number(limit)||20));store.setProperty(key,JSON.stringify({runId:runId,state:"RUNNING",startRow:first,limit:size,startedAt:new Date().toISOString()}));try{const count=Math.max(0,Math.min(size,sh.getLastRow()-first+1)),rows=count?sh.getRange(first,1,count,sh.getLastColumn()).getValues():[],ids=rows.filter(function(r){const x=canonicalWoS63Text_(r[id]);return canonicalWoS63Text_(r[status])===WorkOrderStatus.SELESAI&&!canonicalWoS63Text_(r[si])&&!canonicalWoS63Text_(r[sn])&&x!=="WO2608140015"&&x!=="WO2608200012";}).map(function(r){return canonicalWoS63Text_(r[id]);}),out={runId:runId,state:"PASS",startRow:first,limit:size,rowsScanned:count,candidateCount:ids.length,candidateIdsJson:JSON.stringify(ids),nextStartRow:first+count,hasMore:first+count<=sh.getLastRow(),finishedAt:new Date().toISOString()};store.setProperty(key,JSON.stringify(out));return out;}catch(e){const out={runId:runId,state:"FAIL",startRow:first,limit:size,error:String(e.message||e),finishedAt:new Date().toISOString()};store.setProperty(key,JSON.stringify(out));throw e;}}
function auditCanonicalWorkOrderSettlementS63TimeoutCli(){
  const workOrderSheet=WorkOrderRepository.sheet(), woColumns=WorkOrderRepository.getColumnMap_(), salesSheet=PenjualanRepository.getHeaderSheet(), salesColumns=PenjualanRepository.getColumnMap_(salesSheet), detailsSheet=PenjualanRepository.getDetailSheet();
  const salesRows=salesSheet.getLastRow()<2?[]:salesSheet.getRange(2,1,salesSheet.getLastRow()-1,salesSheet.getLastColumn()).getValues();
  const candidates=salesRows.map(function(row){return {salesNumber:canonicalWoS63Text_(row[salesColumns.NoTransaksi]),submissionId:canonicalWoS63Text_(row[salesColumns.SubmissionId]),workOrderId:canonicalWoS63Text_(row[salesColumns.WorkOrder]),fingerprint:canonicalWoS63Text_(row[salesColumns.PayloadFingerprint]),status:canonicalWoS63Text_(row[salesColumns.Status]),createdAt:String(row[salesColumns.CreatedAt]||"")};}).filter(function(row){return row.submissionId.indexOf("S6-3-")===0||row.submissionId.indexOf("S6.3")===0;});
  const latest=candidates[candidates.length-1];if(!latest)return {classification:"NO_FIXTURE",fixtureFound:false,stock:BarangRepository.getStock("BRG000097"),ledgerCount:StockLedgerRepository.sheet().getLastRow()};
  const metadata=WorkOrderRepository.getSettlementMetadata(latest.workOrderId), details=PenjualanRepository.findItemsBySalesNumber(latest.salesNumber), ledgers=StockLedgerRepository.sheet().getDataRange().getValues().slice(1).filter(function(row){return canonicalWoS63Text_(row[COL_STOK.REFERENSI]).indexOf(latest.salesNumber+":")===0;});
  return {fixtureFound:true,classification:candidates.filter(function(row){return row.workOrderId===latest.workOrderId;}).length>1?"ANOMALY":(details.length&&metadata&&canonicalWoS63Text_(metadata.settlementSalesNumber)===latest.salesNumber?"COMPLETE_PREPARATION":"PARTIAL_PREPARATION"),workOrderId:latest.workOrderId,submissionId:latest.submissionId,settlementIdentity:metadata&&metadata.settlementIdentity||"",settlementFingerprint:latest.fingerprint,salesNumber:latest.salesNumber,salesStatus:latest.status,headerCount:candidates.length,detailCount:details.length,workOrderSettlementStatus:metadata&&metadata.settlementStatus||"",workOrderSettlementSalesNumber:metadata&&metadata.settlementSalesNumber||"",workOrderSettlementFingerprint:metadata&&metadata.settlementFingerprint||"",stockBRG000097:BarangRepository.getStock("BRG000097"),settlementLedgerCount:ledgers.length,wopRowCount:getSheet_(CONFIG.SHEET.WORK_ORDER_PART).getLastRow(),detailSheetRows:detailsSheet.getLastRow(),candidates:candidates};
}
