/** Read-only Phase 1 runners for S6.3 final fixture matrix. */
function canonicalWoS63FinalText_(value){return String(value === undefined || value === null ? "" : value).trim();}
function runCanonicalWorkOrderSettlementHistoricalWoReadableCli(){
    const row = WorkOrderRepository.findAll().find(function(item){
        const id = canonicalWoS63FinalText_(item[COL_WORK_ORDER.ID]);
        const metadata = id ? WorkOrderRepository.getSettlementMetadata(id) : null;
        return id && metadata && !canonicalWoS63FinalText_(metadata.settlementIdentity) && !canonicalWoS63FinalText_(metadata.settlementSalesNumber) && !canonicalWoS63FinalText_(metadata.settlementFingerprint);
    });
    if(!row){throw new Error("Historical Work Order tanpa metadata settlement tidak ditemukan.");}
    const workOrderId = canonicalWoS63FinalText_(row[COL_WORK_ORDER.ID]);
    const readable = WorkOrderRepository.findById(workOrderId);
    if(!readable){throw new Error("Historical Work Order tidak dapat dibaca.");}
    const metadata = WorkOrderRepository.getSettlementMetadata(workOrderId);
    if(canonicalWoS63FinalText_(metadata.settlementIdentity) || canonicalWoS63FinalText_(metadata.settlementSalesNumber) || canonicalWoS63FinalText_(metadata.settlementFingerprint)){throw new Error("Historical Work Order memiliki metadata settlement.");}
    return {success:true,workOrderId:workOrderId,status:canonicalWoS63FinalText_(readable[COL_WORK_ORDER.STATUS]),settlementIdentity:"",settlementSalesNumber:"",settlementFingerprint:"",message:"HISTORICAL_WO_READABLE PASS"};
}
function runCanonicalWorkOrderSettlementHistoricalSalesReadableCli(){
    const sheet = PenjualanRepository.getHeaderSheet(), columns = PenjualanRepository.getColumnMap_(sheet);
    const row = sheet.getLastRow() < 2 ? null : sheet.getRange(2,1,sheet.getLastRow()-1,sheet.getLastColumn()).getValues().find(function(item){
        return canonicalWoS63FinalText_(item[columns.NoTransaksi]) && !canonicalWoS63FinalText_(item[columns.SubmissionId]) && !canonicalWoS63FinalText_(item[columns.IdempotencyKey]) && !canonicalWoS63FinalText_(item[columns.TransactionId]) && !canonicalWoS63FinalText_(item[columns.PayloadFingerprint]);
    });
    if(!row){throw new Error("Historical Sales tanpa canonical metadata tidak ditemukan.");}
    const salesNumber = canonicalWoS63FinalText_(row[columns.NoTransaksi]), readable = PenjualanRepository.findBySalesNumber(salesNumber);
    if(!readable || PenjualanRepository.findBySubmissionId("")){throw new Error("Historical Sales tidak kompatibel.");}
    return {success:true,salesNumber:salesNumber,status:canonicalWoS63FinalText_(readable.status),submissionId:"",idempotencyKey:"",transactionId:"",payloadFingerprint:"",message:"HISTORICAL_SALES_READABLE PASS"};
}

const CANONICAL_WO_S63_M3 = {jasaWo:"WO2608220003",jasaLine:"WOJ2608220001",wopWo:"WO2608220004",wopLine:"WOP2608220003",recoveryWo:"WO2608220005",barangId:"BRG000163",seedLedger:"STK2608220118",serviceLedger:"STK2608220119",actor:"S6.3_TEST"};
function canonicalWoS63M3Assert_(condition,message){if(!condition)throw new Error(message);}
function canonicalWoS63M3StockSnapshot_(){return {brg001:Number(BarangRepository.getStock("BRG000001")),brg097:Number(BarangRepository.getStock("BRG000097")),brg163:Number(BarangRepository.getStock(CANONICAL_WO_S63_M3.barangId)),ledgerRows:StockLedgerRepository.sheet().getLastRow(),purchaseRows:PurchaseRepository.getHeaderSheet().getLastRow()};}
function canonicalWoS63M3NoInventory_(before,allow163){const after=canonicalWoS63M3StockSnapshot_();canonicalWoS63M3Assert_(after.brg001===before.brg001&&after.brg097===before.brg097&&after.ledgerRows===before.ledgerRows&&after.purchaseRows===before.purchaseRows&&(!allow163?after.brg163===before.brg163:true),"S6.3 preparation/recovery tidak boleh mengubah inventory atau Purchase.");return after;}
function canonicalWoS63M3Input_(workOrderId,submissionId,directSaleItems){return {workOrderId:workOrderId,submissionId:submissionId,directSaleItems:directSaleItems||[],discountType:"NOMINAL",discountValue:0,paymentIntent:{admin:CANONICAL_WO_S63_M3.actor}};}
function canonicalWoS63M3Run_(runId,scenario,fn){return canonicalWoS63Run_(runId,scenario,fn);}
function canonicalWoS63M3Detail_(salesNumber,type){const rows=PenjualanRepository.findItemsBySalesNumber(salesNumber).filter(function(row){return canonicalWoS63FinalText_(row.sourceDocumentType)===type;});canonicalWoS63M3Assert_(rows.length===1,"Detail " + type + " harus tepat satu.");return rows[0];}
function canonicalWoS63M3SalesLedgers_(salesNumber){return StockLedgerRepository.sheet().getDataRange().getValues().slice(1).filter(function(row){return canonicalWoS63FinalText_(row[COL_STOK.REFERENSI]).indexOf(salesNumber+":L")===0;});}
function runCanonicalWorkOrderSettlementM3WoJasaAndDirectCli(runId){return canonicalWoS63M3Run_(runId,"WO_JASA_AND_DIRECT_TRACEABILITY",function(){
    const before=canonicalWoS63M3StockSnapshot_(), barang=BarangRepository.findById(CANONICAL_WO_S63_M3.barangId), masterPrice=Number(barang[COL_BARANG.HARGAJUAL]);
    canonicalWoS63M3Assert_(masterPrice===20000,"Master price dedicated Barang berubah dari fixture.");
    const result=prepareCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.jasaWo,"S6-3-M3-JASA-DIRECT",[{jenis:"BARANG",kode:CANONICAL_WO_S63_M3.barangId,qty:1,harga:99999}]));
    const metadata=WorkOrderRepository.getSettlementMetadata(CANONICAL_WO_S63_M3.jasaWo), reservation=getCanonicalWorkOrderSettlementReservationCli(CANONICAL_WO_S63_M3.jasaWo), jasa=canonicalWoS63M3Detail_(result.salesNumber,"WORK_ORDER_JASA"), direct=canonicalWoS63M3Detail_(result.salesNumber,"DIRECT_SALE"), source=WorkOrderJasaRepository.findById(CANONICAL_WO_S63_M3.jasaLine);
    canonicalWoS63M3Assert_(canonicalWoS63FinalText_(metadata.settlementStatus)==="UNSETTLED"&&metadata.settlementSalesNumber===result.salesNumber&&reservation.propertyExists&&reservation.state==="PREPARED","Preparation WO Jasa tidak menyimpan relation/reservation UNSETTLED.");
    canonicalWoS63M3Assert_(jasa.sourceDocumentId===CANONICAL_WO_S63_M3.jasaWo&&jasa.sourceDocumentLineId===CANONICAL_WO_S63_M3.jasaLine&&jasa.fulfillmentSource==="WORK_ORDER_FULFILLED","Trace WorkOrderJasa tidak valid.");
    canonicalWoS63M3Assert_(Number(jasa.unitPrice)===35000&&Number(source[COL_WO_JASA.HARGA])===35000,"Harga snapshot WorkOrderJasa tidak persisten.");
    canonicalWoS63M3Assert_(direct.sourceDocumentId===result.salesNumber&&direct.sourceDocumentLineId===direct.lineId&&direct.fulfillmentSource==="DIRECT_SALE"&&Number(direct.unitPrice)===masterPrice&&Number(direct.unitPrice)!==99999,"Direct Sale tidak memakai harga Master authoritative.");
    canonicalWoS63M3Assert_(canonicalWoS63M3SalesLedgers_(result.salesNumber).length===0,"Preparation tidak boleh membuat Sales ledger.");canonicalWoS63M3NoInventory_(before);
    return {salesNumber:result.salesNumber,state:result.state,woJasaPrice:Number(jasa.unitPrice),masterJasaPrice:Number(source[COL_WO_JASA.HARGA]),directClientPrice:99999,directPersistedMasterPrice:Number(direct.unitPrice),salesLedgerCount:0};
});}
function runCanonicalWorkOrderSettlementM3WopTraceabilityCli(runId){return canonicalWoS63M3Run_(runId,"WOP_TRACEABILITY",function(){
    const before=canonicalWoS63M3StockSnapshot_(), part=WorkOrderPartRepository.findById(CANONICAL_WO_S63_M3.wopLine), service=StockLedgerRepository.findByReferensiFresh(CANONICAL_WO_S63_M3.wopLine).filter(function(row){return canonicalWoS63FinalText_(row[COL_STOK.JENISMUTASI])==="SERVICE";}), reversal=StockLedgerRepository.findByReferensiFresh(CANONICAL_WO_S63_M3.wopLine).filter(function(row){return canonicalWoS63FinalText_(row[COL_STOK.JENISMUTASI])==="REVERSAL";});
    canonicalWoS63M3Assert_(before.brg163===9&&part&&canonicalWoS63FinalText_(part[COL_WORK_ORDER_PART.STATUS])===WorkOrderPartStatus.DONE&&service.length===1&&reversal.length===0&&Number(service[0][COL_STOK.STOKAWAL])===10&&Number(service[0][COL_STOK.STOKAKHIR])===9,"Pre-guard WOP fixture tidak sesuai.");
    const result=prepareCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.wopWo,"S6-3-M3-WOP",[])), metadata=WorkOrderRepository.getSettlementMetadata(CANONICAL_WO_S63_M3.wopWo), reservation=getCanonicalWorkOrderSettlementReservationCli(CANONICAL_WO_S63_M3.wopWo), detail=canonicalWoS63M3Detail_(result.salesNumber,"WORK_ORDER_PART");
    canonicalWoS63M3Assert_(metadata.settlementStatus==="UNSETTLED"&&reservation.propertyExists&&reservation.state==="PREPARED","Preparation WOP relation/reservation tidak valid.");
    canonicalWoS63M3Assert_(detail.sourceDocumentId===CANONICAL_WO_S63_M3.wopWo&&detail.sourceDocumentLineId===CANONICAL_WO_S63_M3.wopLine&&detail.workOrderPartId===CANONICAL_WO_S63_M3.wopLine&&detail.fulfillmentSource==="WORK_ORDER_FULFILLED","Trace WorkOrderPart tidak valid.");
    canonicalWoS63M3Assert_(canonicalWoS63M3SalesLedgers_(result.salesNumber).length===0,"Settlement WOP membuat Sales stock movement.");canonicalWoS63M3NoInventory_(before);
    return {salesNumber:result.salesNumber,state:result.state,workOrderPartId:CANONICAL_WO_S63_M3.wopLine,serviceLedgerId:canonicalWoS63FinalText_(service[0][COL_STOK.ID]),salesLedgerCount:0,dedicatedStock:Number(BarangRepository.getStock(CANONICAL_WO_S63_M3.barangId))};
});}
function runCanonicalWorkOrderSettlementM3WopCompensationCli(runId){return canonicalWoS63M3Run_(runId,"WOP_TEST_COMPENSATION",function(){
    const reference="S63_TEST_CLEANUP:"+CANONICAL_WO_S63_M3.wopLine+":DONE_WOP", before=Number(BarangRepository.getStock(CANONICAL_WO_S63_M3.barangId)), service=StockLedgerRepository.findByReferensiFresh(CANONICAL_WO_S63_M3.wopLine).filter(function(row){return canonicalWoS63FinalText_(row[COL_STOK.JENISMUTASI])==="SERVICE";}), existing=StockLedgerRepository.findByReferensiFresh(reference);
    canonicalWoS63M3Assert_(before===9&&service.length===1&&Number(service[0][COL_STOK.STOKAWAL])===10&&Number(service[0][COL_STOK.STOKAKHIR])===9&&existing.length===0,"Preflight kompensasi WOP tidak sesuai.");
    InventoryService.moveStock({kodeBarang:CANONICAL_WO_S63_M3.barangId,movementType:MovementType.PURCHASE,qty:1,reference:reference,note:"S6.3 test fixture compensation after DONE WOP settlement proof; non-production",performedBy:CANONICAL_WO_S63_M3.actor});
    const cleanup=StockLedgerRepository.findByReferensiFresh(reference), part=WorkOrderPartRepository.findById(CANONICAL_WO_S63_M3.wopLine), after=Number(BarangRepository.getStock(CANONICAL_WO_S63_M3.barangId));
    canonicalWoS63M3Assert_(cleanup.length===1&&Number(cleanup[0][COL_STOK.QTYMASUK])===1&&Number(cleanup[0][COL_STOK.STOKAWAL])===9&&Number(cleanup[0][COL_STOK.STOKAKHIR])===10&&after===10&&canonicalWoS63FinalText_(part[COL_WORK_ORDER_PART.STATUS])===WorkOrderPartStatus.DONE,"Kompensasi WOP tidak auditable atau lifecycle berubah.");
    return {cleanupLedgerId:canonicalWoS63FinalText_(cleanup[0][COL_STOK.ID]),reference:reference,stokAwal:9,stokAkhir:10,dedicatedStock:after};
});}
function canonicalWoS63M3RecoveryPlan_(){const plan=planCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.recoveryWo,"S6-3-M3-RECOVERY",[]));canonicalWoS63M3Assert_(plan.eligible,"Fixture recovery tidak eligible: "+plan.errors.join(" | "));return plan;}
function canonicalWoS63M3RecoveryClear_(){PropertiesService.getScriptProperties().deleteProperty(CanonicalWorkOrderSettlementPreparationService.reservationKey_(CANONICAL_WO_S63_M3.recoveryWo));WorkOrderRepository.updateSettlementMetadata(CANONICAL_WO_S63_M3.recoveryWo,{settlementStatus:"",settlementIdentity:"",settlementSalesNumber:"",settlementFingerprint:"",settledAt:""});}
function canonicalWoS63M3RecoveryNoSales_(){return PenjualanRepository.findSettlementSalesByWorkOrder(CANONICAL_WO_S63_M3.recoveryWo);}
function runCanonicalWorkOrderSettlementM3RecoveryPreparedWithoutSalesCli(runId){return canonicalWoS63M3Run_(runId,"RECOVERY_PREPARED_WITHOUT_SALES",function(){const before=canonicalWoS63M3StockSnapshot_(),plan=canonicalWoS63M3RecoveryPlan_();canonicalWoS63M3Assert_(canonicalWoS63M3RecoveryNoSales_().length===0,"Recovery PREPARED tanpa Sales harus dijalankan sebelum Sales fixture dibuat.");CanonicalWorkOrderSettlementPreparationService.writeReservation_(plan,"S6TEST-ABSENT-PREPARED","PREPARED");let blocked=false;try{prepareCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.recoveryWo,"S6-3-M3-RECOVERY",[]));}catch(e){blocked=canonicalWoS63FinalText_(e.message).indexOf("RECOVERY_REQUIRED")>=0;}finally{canonicalWoS63M3RecoveryClear_();}canonicalWoS63M3Assert_(blocked&&canonicalWoS63M3RecoveryNoSales_().length===0,"PREPARED tanpa Sales tidak diblokir aman.");canonicalWoS63M3NoInventory_(before);return {blocked:true,state:"RECOVERY_REQUIRED"};});}
function runCanonicalWorkOrderSettlementM3RecoveryRelationWithoutSalesCli(runId){return canonicalWoS63M3Run_(runId,"RECOVERY_RELATION_WITHOUT_SALES",function(){const before=canonicalWoS63M3StockSnapshot_(),plan=canonicalWoS63M3RecoveryPlan_();canonicalWoS63M3Assert_(canonicalWoS63M3RecoveryNoSales_().length===0,"Relation tanpa Sales harus dijalankan sebelum Sales fixture dibuat.");WorkOrderRepository.updateSettlementMetadata(CANONICAL_WO_S63_M3.recoveryWo,{settlementStatus:"UNSETTLED",settlementIdentity:plan.settlementIdentity,settlementSalesNumber:"S6TEST-ABSENT-RELATION",settlementFingerprint:plan.settlementFingerprint,settledAt:""});let blocked=false;try{prepareCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.recoveryWo,"S6-3-M3-RECOVERY",[]));}catch(e){blocked=canonicalWoS63FinalText_(e.message).indexOf("RECOVERY_REQUIRED")>=0;}finally{canonicalWoS63M3RecoveryClear_();}canonicalWoS63M3Assert_(blocked&&canonicalWoS63M3RecoveryNoSales_().length===0,"Relation tanpa Sales tidak diblokir aman.");canonicalWoS63M3NoInventory_(before);return {blocked:true,state:"RECOVERY_REQUIRED"};});}
function runCanonicalWorkOrderSettlementM3RecoveryReservedWithoutSalesCli(runId){return canonicalWoS63M3Run_(runId,"RECOVERY_RESERVED_WITHOUT_SALES",function(){const before=canonicalWoS63M3StockSnapshot_(),plan=canonicalWoS63M3RecoveryPlan_();canonicalWoS63M3Assert_(canonicalWoS63M3RecoveryNoSales_().length===0,"RESERVED fixture harus belum memiliki Sales.");const reserved=RunningNumberService.generate(DocumentType.SALES);CanonicalWorkOrderSettlementPreparationService.writeReservation_(plan,reserved,"RESERVED");const result=prepareCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.recoveryWo,"S6-3-M3-RECOVERY",[])), property=getCanonicalWorkOrderSettlementReservationCli(CANONICAL_WO_S63_M3.recoveryWo), metadata=WorkOrderRepository.getSettlementMetadata(CANONICAL_WO_S63_M3.recoveryWo);canonicalWoS63M3Assert_(result.state==="PREPARED"&&result.salesNumber===reserved&&canonicalWoS63M3RecoveryNoSales_().length===1&&property.state==="PREPARED"&&metadata.settlementStatus==="UNSETTLED","RESERVED tanpa Sales tidak recover dengan nomor yang sama.");canonicalWoS63M3NoInventory_(before);return {salesNumber:reserved,state:result.state,reservationState:property.state};});}
function runCanonicalWorkOrderSettlementM3RecoveryMissingPropertyCli(runId){return canonicalWoS63M3Run_(runId,"RECOVERY_MISSING_PROPERTY",function(){const before=canonicalWoS63M3StockSnapshot_(),sales=canonicalWoS63M3RecoveryNoSales_();canonicalWoS63M3Assert_(sales.length===1,"Missing property membutuhkan tepat satu Sales fixture.");const number=sales[0].salesNumber;PropertiesService.getScriptProperties().deleteProperty(CanonicalWorkOrderSettlementPreparationService.reservationKey_(CANONICAL_WO_S63_M3.recoveryWo));const result=prepareCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.recoveryWo,"S6-3-M3-RECOVERY",[])),property=getCanonicalWorkOrderSettlementReservationCli(CANONICAL_WO_S63_M3.recoveryWo);canonicalWoS63M3Assert_(result.state==="RESUMED"&&result.salesNumber===number&&property.state==="PREPARED"&&property.salesNumber===number&&canonicalWoS63M3RecoveryNoSales_().length===1,"Property missing tidak direbuild aman.");canonicalWoS63M3NoInventory_(before);return {salesNumber:number,state:result.state,reservationState:property.state};});}
function runCanonicalWorkOrderSettlementM3RecoverySalesWithoutRelationCli(runId){return canonicalWoS63M3Run_(runId,"RECOVERY_SALES_WITHOUT_RELATION",function(){const before=canonicalWoS63M3StockSnapshot_(),sales=canonicalWoS63M3RecoveryNoSales_();canonicalWoS63M3Assert_(sales.length===1,"Sales without relation membutuhkan tepat satu Sales fixture.");const number=sales[0].salesNumber;WorkOrderRepository.updateSettlementMetadata(CANONICAL_WO_S63_M3.recoveryWo,{settlementStatus:"",settlementIdentity:"",settlementSalesNumber:"",settlementFingerprint:"",settledAt:""});const result=prepareCanonicalWorkOrderSettlement(canonicalWoS63M3Input_(CANONICAL_WO_S63_M3.recoveryWo,"S6-3-M3-RECOVERY",[])),metadata=WorkOrderRepository.getSettlementMetadata(CANONICAL_WO_S63_M3.recoveryWo);canonicalWoS63M3Assert_(result.state==="RESUMED"&&result.salesNumber===number&&canonicalWoS63M3RecoveryNoSales_().length===1&&metadata.settlementStatus==="UNSETTLED"&&metadata.settlementSalesNumber===number,"Sales tanpa relation tidak memulihkan relation aman.");canonicalWoS63M3NoInventory_(before);return {salesNumber:number,state:result.state,settlementStatus:metadata.settlementStatus};});}

function runCanonicalWorkOrderSettlementM3WoJasaAndDirectCliNoArgs(){return runCanonicalWorkOrderSettlementM3WoJasaAndDirectCli("S6-M3-JASA-DIRECT-001");}
function runCanonicalWorkOrderSettlementM3WopTraceabilityCliNoArgs(){return runCanonicalWorkOrderSettlementM3WopTraceabilityCli("S6-M3-WOP-TRACE-001");}
function runCanonicalWorkOrderSettlementM3WopCompensationCliNoArgs(){return runCanonicalWorkOrderSettlementM3WopCompensationCli("S6-M3-WOP-CLEANUP-001");}
function runCanonicalWorkOrderSettlementM3RecoveryPreparedWithoutSalesCliNoArgs(){return runCanonicalWorkOrderSettlementM3RecoveryPreparedWithoutSalesCli("S6-M3-RECOVERY-PREPARED-001");}
function runCanonicalWorkOrderSettlementM3RecoveryRelationWithoutSalesCliNoArgs(){return runCanonicalWorkOrderSettlementM3RecoveryRelationWithoutSalesCli("S6-M3-RECOVERY-RELATION-001");}
function runCanonicalWorkOrderSettlementM3RecoveryReservedWithoutSalesCliNoArgs(){return runCanonicalWorkOrderSettlementM3RecoveryReservedWithoutSalesCli("S6-M3-RECOVERY-RESERVED-001");}
function runCanonicalWorkOrderSettlementM3RecoveryMissingPropertyCliNoArgs(){return runCanonicalWorkOrderSettlementM3RecoveryMissingPropertyCli("S6-M3-RECOVERY-MISSING-001");}
function runCanonicalWorkOrderSettlementM3RecoverySalesWithoutRelationCliNoArgs(){return runCanonicalWorkOrderSettlementM3RecoverySalesWithoutRelationCli("S6-M3-RECOVERY-SALES-RELATION-001");}

function auditCanonicalWorkOrderSettlementM3ABarangPriceCli(){
    const barangId="BRG000163", repository=BarangRepository.findById(barangId);
    if(!repository){throw new Error("BRG000163 tidak ditemukan.");}
    const active=SpreadsheetApp.getActiveSpreadsheet(), fresh=SpreadsheetApp.openById(active.getId()), sheet=fresh.getSheetByName(CONFIG.SHEET.BARANG);
    if(!sheet){throw new Error("Sheet MasterBarang tidak ditemukan.");}
    const headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0], idColumn=headers.indexOf("ID")>=0?headers.indexOf("ID"):0, rows=sheet.getLastRow()<2?[]:sheet.getRange(2,1,sheet.getLastRow()-1,sheet.getLastColumn()).getValues(), rowIndex=rows.findIndex(function(row){return canonicalWoS63FinalText_(row[idColumn])===barangId;});
    if(rowIndex<0){throw new Error("BRG000163 tidak ditemukan pada fresh sheet.");}
    const physicalRow=rowIndex+2, values=sheet.getRange(physicalRow,1,1,sheet.getLastColumn()).getValues()[0], formulas=sheet.getRange(physicalRow,1,1,sheet.getLastColumn()).getFormulas()[0], column=function(names){for(let i=0;i<names.length;i++){const index=headers.indexOf(names[i]);if(index>=0)return index;}return -1;}, modalColumn=column(["HargaModal","Harga Modal"]), jualColumn=column(["HargaJual","Harga Jual"]), pricingColumn=column(["PricingMode","Pricing Mode"]);
    const ledger=StockLedgerRepository.findByReferensiFresh("S63_TEST_SEED:S63_TEST_BARANG_WOP"), wop=StockLedgerRepository.findByReferensiFresh("WOP2608220003"), cleanup=StockLedgerRepository.findByReferensiFresh("S63_TEST_CLEANUP:WOP2608220003:DONE_WOP"), service=wop.filter(function(row){return canonicalWoS63FinalText_(row[COL_STOK.JENISMUTASI])==="SERVICE";}), reversal=wop.filter(function(row){return canonicalWoS63FinalText_(row[COL_STOK.JENISMUTASI])==="REVERSAL";});
    const salesBefore=PenjualanRepository.findSettlementSalesByWorkOrder("WO2608220003").length+PenjualanRepository.findSettlementSalesByWorkOrder("WO2608220004").length+PenjualanRepository.findSettlementSalesByWorkOrder("WO2608220005").length, metaJasa=WorkOrderRepository.getSettlementMetadata("WO2608220003"),metaWop=WorkOrderRepository.getSettlementMetadata("WO2608220004"),metaRecovery=WorkOrderRepository.getSettlementMetadata("WO2608220005"),reservationJasa=getCanonicalWorkOrderSettlementReservationCli("WO2608220003"),reservationWop=getCanonicalWorkOrderSettlementReservationCli("WO2608220004"),reservationRecovery=getCanonicalWorkOrderSettlementReservationCli("WO2608220005");
    return {barangId:barangId,nama:canonicalWoS63FinalText_(repository[COL_BARANG.NAMA]),status:canonicalWoS63FinalText_(repository[COL_BARANG.STATUS]),hargaModal:Number(repository[COL_BARANG.HARGAMODAL]),hargaJual:Number(repository[COL_BARANG.HARGAJUAL]),pricingMode:pricingColumn>=0?canonicalWoS63FinalText_(values[pricingColumn]):"",stock:Number(repository[COL_BARANG.STOK]),satuan:canonicalWoS63FinalText_(repository[COL_BARANG.SATUAN]),createdBy:canonicalWoS63FinalText_(repository[COL_BARANG.CREATED_BY]),catatan:canonicalWoS63FinalText_(repository[COL_BARANG.CATATAN]),repositoryHargaJual:Number(repository[COL_BARANG.HARGAJUAL]),freshSheetHargaJual:jualColumn>=0?Number(values[jualColumn]):null,physicalRow:physicalRow,physicalHeadersJson:JSON.stringify(headers),physicalRowValuesJson:JSON.stringify(values),physicalRowFormulasJson:JSON.stringify(formulas),physicalHargaModal:modalColumn>=0?values[modalColumn]:null,physicalHargaJual:jualColumn>=0?values[jualColumn]:null,physicalPricingMode:pricingColumn>=0?values[pricingColumn]:"",hargaModalFormula:modalColumn>=0?formulas[modalColumn]:"",hargaJualFormula:jualColumn>=0?formulas[jualColumn]:"",seedCount:ledger.length,seedStokAwal:ledger.length?Number(ledger[0][COL_STOK.STOKAWAL]):null,seedStokAkhir:ledger.length?Number(ledger[0][COL_STOK.STOKAKHIR]):null,serviceCount:service.length,serviceStokAwal:service.length?Number(service[0][COL_STOK.STOKAWAL]):null,serviceStokAkhir:service.length?Number(service[0][COL_STOK.STOKAKHIR]):null,reversalCount:reversal.length,cleanupCount:cleanup.length,guardBRG000001:Number(BarangRepository.getStock("BRG000001")),guardBRG000097:Number(BarangRepository.getStock("BRG000097")),salesCount:salesBefore,reservationCount:(reservationJasa.propertyExists?1:0)+(reservationWop.propertyExists?1:0)+(reservationRecovery.propertyExists?1:0),relationPresent:(metaJasa.settlementIdentity||metaWop.settlementIdentity||metaRecovery.settlementIdentity)?true:false,currentAuthoritativeDirectSalePrice:Number(repository[COL_BARANG.HARGAJUAL])};
}
