function canonicalSalesS5Assert_(value,message){if(!value)throw new Error("Canonical Sales S5 gagal: "+message);}
const CANONICAL_SALES_S5_TEST_BARANG_ID="BRG000097";
function canonicalSalesS5Fixture_(suffix){return {submissionId:"S5-"+suffix+"-"+Date.now(),pelanggan:{id:"CUS-S5",nama:"S5"},kendaraan:{id:"VEH-S5",platNomor:"S5"},transaksi:{metodeBayar:"TUNAI",bayar:999999999,admin:"S5_TEST",mekanikUtama:""},items:[{jenis:"BARANG",kode:CANONICAL_SALES_S5_TEST_BARANG_ID,qty:1,harga:1,nama:"CLIENT_TIDAK_AUTHORITATIVE"}]};}
function canonicalSalesS5Cleanup_(result,qty,barangId){InventoryService.moveStock({kodeBarang:barangId||CANONICAL_SALES_S5_TEST_BARANG_ID,movementType:MovementType.PURCHASE,qty:qty,reference:"S5_TEST_CLEANUP:"+result.salesNumber,note:"Canonical Sales S5 compensating stock IN",performedBy:"S5_TEST"});}
function canonicalSalesS5DirectUnsafe_(){const before=BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID),p=canonicalSalesS5Fixture_("DIRECT"),r=TransactionService.saveTransaction(p),rows=StockLedgerRepository.findByReferensiFresh(r.salesNumber+":L001");canonicalSalesS5Assert_(r.status===SalesStatus.LUNAS&&rows.length===1&&Number(rows[0][COL_STOK.QTYKELUAR])===1,"Direct sale tidak commit tepat sekali.");canonicalSalesS5Assert_(Number(PenjualanRepository.findItemsBySalesNumber(r.salesNumber)[0].unitPrice)!==1,"Harga client dipakai sebagai authoritative.");canonicalSalesS5Cleanup_(r,1,CANONICAL_SALES_S5_TEST_BARANG_ID);canonicalSalesS5Assert_(Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===Number(before),"Cleanup stok gagal.");return {success:true,salesNumber:r.salesNumber,cleanupQty:1};}
function canonicalSalesS5FreshStock_(barangId){
  const ss=SpreadsheetApp.getActiveSpreadsheet();
  const fresh=SpreadsheetApp.openById(ss.getId()).getSheetByName(CONFIG.SHEET.BARANG);
  const row=fresh.getDataRange().getValues().slice(1).find(function(item){return String(item[COL_BARANG.ID]||"").trim()===String(barangId);});
  return row ? Number(row[COL_BARANG.STOK]) : null;
}
function canonicalSalesS5RetryUnsafe_(){
  const p=canonicalSalesS5Fixture_("RETRY"), barangId=CANONICAL_SALES_S5_TEST_BARANG_ID, qty=1, statusKey="CANONICAL_SALES:S5:RETRY:"+p.submissionId, store=PropertiesService.getScriptProperties();
  const result={success:false,submissionId:p.submissionId,salesNumber:"",barangId:barangId,qty:qty,stockBefore:null,stockAfterFirst:null,stockAfterRetry:null,stockAfterCleanup:null,finalNormalStock:null,finalFreshStock:null,alreadyRecorded:false,saleLedgerId:"",saleLedgerCount:0,saleQtyOut:0,saleStokAwal:null,saleStokAkhir:null,cleanupLedgerId:"",cleanupLedgerCount:0,cleanupQtyIn:0,cleanupStokAwal:null,cleanupStokAkhir:null};
  store.setProperty(statusKey,JSON.stringify({status:"RUNNING",result:result}));
  try{
    result.stockBefore=canonicalSalesS5FreshStock_(barangId);
    const first=TransactionService.saveTransaction(p);result.salesNumber=first.salesNumber;result.stockAfterFirst=canonicalSalesS5FreshStock_(barangId);
    canonicalSalesS5Assert_(first.status===SalesStatus.LUNAS,"A. first submit tidak LUNAS.");
    const retry=TransactionService.saveTransaction(p);result.stockAfterRetry=canonicalSalesS5FreshStock_(barangId);result.alreadyRecorded=!!retry.alreadyRecorded;
    canonicalSalesS5Assert_(retry.salesNumber===first.salesNumber,"B. retry memakai salesNumber berbeda.");
    canonicalSalesS5Assert_(result.alreadyRecorded,"C. retry tidak alreadyRecorded.");
    const saleRows=StockLedgerRepository.findByReferensiFresh(first.salesNumber+":L001");result.saleLedgerCount=saleRows.length;
    canonicalSalesS5Assert_(saleRows.length===1,"D. canonical SALE ledger tidak tepat satu.");
    const sale=saleRows[0];result.saleLedgerId=String(sale[COL_STOK.ID]||"");result.saleQtyOut=Number(sale[COL_STOK.QTYKELUAR]||0);result.saleStokAwal=Number(sale[COL_STOK.STOKAWAL]);result.saleStokAkhir=Number(sale[COL_STOK.STOKAKHIR]);result.saleCount=result.saleLedgerCount;
    canonicalSalesS5Assert_(result.saleStokAkhir===result.saleStokAwal-qty,"E. canonical SALE ledger tidak mengurangi stok tepat sekali.");
    const cleanupReference="S5_TEST_CLEANUP:"+first.salesNumber;canonicalSalesS5Assert_(StockLedgerRepository.findByReferensiFresh(cleanupReference).length===0,"F. cleanup reference sudah ada sebelum cleanup.");
    canonicalSalesS5Cleanup_(first,qty);result.stockAfterCleanup=canonicalSalesS5FreshStock_(barangId);
    const cleanupRows=StockLedgerRepository.findByReferensiFresh(cleanupReference);result.cleanupLedgerCount=cleanupRows.length;canonicalSalesS5Assert_(cleanupRows.length===1,"G. cleanup PURCHASE ledger tidak tepat satu.");
    const cleanup=cleanupRows[0];result.cleanupLedgerId=String(cleanup[COL_STOK.ID]||"");result.cleanupQtyIn=Number(cleanup[COL_STOK.QTYMASUK]||0);result.cleanupStokAwal=Number(cleanup[COL_STOK.STOKAWAL]);result.cleanupStokAkhir=Number(cleanup[COL_STOK.STOKAKHIR]);result.cleanupCount=result.cleanupLedgerCount;
    canonicalSalesS5Assert_(result.cleanupQtyIn===result.saleQtyOut,"H. qty cleanup tidak sama dengan SALE.");
    canonicalSalesS5Assert_(result.cleanupStokAkhir===result.cleanupStokAwal+qty,"I. cleanup ledger tidak menambah stok tepat sekali.");
    const allLedger=StockLedgerRepository.sheet().getDataRange().getValues().slice(1),saleIndex=allLedger.findIndex(function(row){return String(row[COL_STOK.ID])===result.saleLedgerId;}),cleanupIndex=allLedger.findIndex(function(row){return String(row[COL_STOK.ID])===result.cleanupLedgerId;});
    result.interveningLedgerCount=Math.max(0,cleanupIndex-saleIndex-1);canonicalSalesS5Assert_(result.interveningLedgerCount===0&&result.cleanupStokAkhir===result.saleStokAwal,"I. TEST_ISOLATION_INTERFERENCE antara SALE dan cleanup.");
    result.finalNormalStock=Number(BarangRepository.getStock(barangId));result.finalFreshStock=canonicalSalesS5FreshStock_(barangId);
    canonicalSalesS5Assert_(result.finalNormalStock===result.finalFreshStock,"J. normal dan fresh stock berbeda.");
    result.success=true;store.setProperty(statusKey,JSON.stringify({status:"PASS",result:result}));return result;
  }catch(error){result.finalNormalStock=Number(BarangRepository.getStock(barangId));result.finalFreshStock=canonicalSalesS5FreshStock_(barangId);store.setProperty(statusKey,JSON.stringify({status:"FAIL",result:result,error:String(error.message||error)}));throw error;}
}
function runCanonicalSalesS5ApprovedCleanupSO0035Cli(){
  const barangId="BRG000097",salesNumber="SO2608220035",saleReference=salesNumber+":L001",cleanupReference="S5_TEST_CLEANUP:"+salesNumber;
  const before=canonicalSalesS5FreshStock_(barangId),sale=StockLedgerRepository.findByReferensiFresh(saleReference),existing=StockLedgerRepository.findByReferensiFresh(cleanupReference);
  if(before!==29||sale.length!==1||Number(sale[0][COL_STOK.STOKAWAL])!==30||Number(sale[0][COL_STOK.STOKAKHIR])!==29||Number(sale[0][COL_STOK.QTYKELUAR])!==1||existing.length!==0)throw new Error("S5.2B cleanup preflight tidak sesuai.");
  canonicalSalesS5Cleanup_({salesNumber:salesNumber},1,barangId);const cleanup=StockLedgerRepository.findByReferensiFresh(cleanupReference),after=canonicalSalesS5FreshStock_(barangId);
  if(cleanup.length!==1||Number(cleanup[0][COL_STOK.QTYMASUK])!==1||Number(cleanup[0][COL_STOK.STOKAWAL])!==29||Number(cleanup[0][COL_STOK.STOKAKHIR])!==30||after!==30)throw new Error("S5.2B cleanup verification gagal.");
  return {success:true,salesNumber:salesNumber,barangId:barangId,cleanupLedgerId:cleanup[0][COL_STOK.ID],stockBefore:before,stockAfter:after};
}
function getCanonicalSalesS5RetryStatusCli(submissionId){const raw=PropertiesService.getScriptProperties().getProperty("CANONICAL_SALES:S5:RETRY:"+String(submissionId||""));return raw?JSON.parse(raw):{status:"NOT_RUN"};}
function runCanonicalSalesS5WopBlockedCli(){const stock=BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID),ledger=StockLedgerRepository.sheet().getLastRow(),p=canonicalSalesS5Fixture_("WOP");p.items[0].fulfillmentSource="WORK_ORDER_FULFILLED";p.items[0].workOrderPartId="WOP-S5";let blocked=false;try{TransactionService.saveTransaction(p);}catch(e){blocked=String(e.message).indexOf("WOP_SETTLEMENT_NOT_AVAILABLE")>=0;}canonicalSalesS5Assert_(blocked&&BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID)===stock&&StockLedgerRepository.sheet().getLastRow()===ledger,"WOP settlement tidak diblokir aman.");return {success:true,blocked:true};}
function canonicalSalesS5FinalizationRecoveryUnsafe_(){const before=BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID),p=canonicalSalesS5Fixture_("FINALIZE"),service=CanonicalSalesProductionService;service.setTestHooksForTest_({beforeFinalize:function(){throw new Error("S5_TEST_FINALIZE_FAILURE");}});let failed=false;try{TransactionService.saveTransaction(p);}catch(e){failed=String(e.message).indexOf("S5_TEST_FINALIZE_FAILURE")>=0;}service.setTestHooksForTest_(null);canonicalSalesS5Assert_(failed,"Failure seam finalization tidak bekerja.");const r=TransactionService.saveTransaction(p),rows=StockLedgerRepository.findByReferensiFresh(r.salesNumber+":L001");canonicalSalesS5Assert_(r.status===SalesStatus.LUNAS&&rows.length===1,"Retry finalization menggandakan atau gagal finalize ledger.");canonicalSalesS5Cleanup_(r,1,CANONICAL_SALES_S5_TEST_BARANG_ID);canonicalSalesS5Assert_(Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===Number(before),"Cleanup finalization gagal.");return {success:true,salesNumber:r.salesNumber};}
function auditCanonicalSalesS5RetryFixtureCli(){
  const sheet=PenjualanRepository.getHeaderSheet(),c=PenjualanRepository.getColumnMap_(sheet),rows=sheet.getDataRange().getValues().slice(1).filter(function(row){return String(row[c.SubmissionId]||"").indexOf("S5-RETRY-")===0;});
  const ss=SpreadsheetApp.getActiveSpreadsheet(),fresh=SpreadsheetApp.openById(ss.getId()),freshBarang=fresh.getSheetByName(CONFIG.SHEET.BARANG),barangRows=freshBarang.getDataRange().getValues().slice(1),barang=barangRows.find(function(row){return String(row[COL_BARANG.ID]||"").trim()==="BRG000001";});
  const fixtures=rows.map(function(row){
    const sales=String(row[c.NoTransaksi]||""), sale=StockLedgerRepository.findByReferensiFresh(sales+":L001"), cleanup=StockLedgerRepository.findByReferensiFresh("S5_TEST_CLEANUP:"+sales);
    const compact=function(x){return {id:x[COL_STOK.ID],type:x[COL_STOK.JENISMUTASI],reference:x[COL_STOK.REFERENSI],in:x[COL_STOK.QTYMASUK],out:x[COL_STOK.QTYKELUAR],before:x[COL_STOK.STOKAWAL],after:x[COL_STOK.STOKAKHIR],delta:Number(x[COL_STOK.STOKAKHIR])-Number(x[COL_STOK.STOKAWAL]),note:x[COL_STOK.KETERANGAN]};};
    return {submissionId:row[c.SubmissionId],salesNumber:sales,status:row[c.Status],transactionId:row[c.TransactionId],sale:sale.map(compact),cleanup:cleanup.map(compact)};
  });
  return {success:true,fixtureCount:rows.length,fixtures:fixtures,normalStock:BarangRepository.getStock("BRG000001"),freshStock:barang?barang[COL_BARANG.STOK]:null};
}

function auditCanonicalSalesS5SO0035FlatCli(){
  const barangId="BRG000097",saleReference="SO2608220035:L001",cleanupReference="S5_TEST_CLEANUP:SO2608220035";
  const compact=function(row){
    if(!row)return {ledgerId:"",movementType:"",reference:"",qtyIn:null,qtyOut:null,stokAwal:null,stokAkhir:null,actualDelta:null};
    const stokAwal=Number(row[COL_STOK.STOKAWAL]),stokAkhir=Number(row[COL_STOK.STOKAKHIR]);
    return {ledgerId:String(row[COL_STOK.ID]||""),movementType:String(row[COL_STOK.JENISMUTASI]||""),reference:String(row[COL_STOK.REFERENSI]||""),qtyIn:Number(row[COL_STOK.QTYMASUK]||0),qtyOut:Number(row[COL_STOK.QTYKELUAR]||0),stokAwal:stokAwal,stokAkhir:stokAkhir,actualDelta:stokAkhir-stokAwal};
  };
  const saleRows=StockLedgerRepository.findByReferensiFresh(saleReference),cleanupRows=StockLedgerRepository.findByReferensiFresh(cleanupReference),sale=compact(saleRows[0]),cleanup=compact(cleanupRows[0]);
  const allRows=StockLedgerRepository.sheet().getDataRange().getValues().slice(1),saleIndex=allRows.findIndex(function(row){return String(row[COL_STOK.ID]||"")===sale.ledgerId;}),barangRows=(saleIndex>=0?allRows.slice(saleIndex):[]).filter(function(row){return String(row[COL_STOK.BARANG_ID]||"")===barangId;}),latest=compact(barangRows.length?barangRows[barangRows.length-1]:null);
  let freshStock=null,freshReadAvailable=false,freshReadError="";
  try{
    const active=SpreadsheetApp.getActiveSpreadsheet(),freshSheet=SpreadsheetApp.openById(active.getId()).getSheetByName(CONFIG.SHEET.BARANG),freshRow=freshSheet.getDataRange().getValues().slice(1).find(function(row){return String(row[COL_BARANG.ID]||"").trim()===barangId;});
    freshStock=freshRow?Number(freshRow[COL_BARANG.STOK]):null;freshReadAvailable=true;
  }catch(error){freshReadError=String(error.message||error);}
  const trace=barangRows.map(function(row){const item=compact(row);return {ledgerId:item.ledgerId,movementType:item.movementType,reference:item.reference,stokAwal:item.stokAwal,stokAkhir:item.stokAkhir,actualDelta:item.actualDelta};});
  return {
    success:true,barangId:barangId,normalStock:Number(BarangRepository.getStock(barangId)),freshStock:freshStock,freshReadAvailable:freshReadAvailable,freshReadError:freshReadError,
    saleCount:saleRows.length,saleLedgerId:sale.ledgerId,saleMovementType:sale.movementType,saleQtyIn:sale.qtyIn,saleQtyOut:sale.qtyOut,saleStokAwal:sale.stokAwal,saleStokAkhir:sale.stokAkhir,saleActualDelta:sale.actualDelta,
    cleanupCount:cleanupRows.length,cleanupLedgerId:cleanup.ledgerId,cleanupMovementType:cleanup.movementType,cleanupQtyIn:cleanup.qtyIn,cleanupQtyOut:cleanup.qtyOut,cleanupStokAwal:cleanup.stokAwal,cleanupStokAkhir:cleanup.stokAkhir,cleanupActualDelta:cleanup.actualDelta,
    latestLedgerId:latest.ledgerId,latestMovementType:latest.movementType,latestReference:latest.reference,latestStokAwal:latest.stokAwal,latestStokAkhir:latest.stokAkhir,latestActualDelta:latest.actualDelta,
    traceJson:JSON.stringify(trace),fixtureSaleDelta:saleRows.length===1?sale.actualDelta:null,fixtureCleanupDelta:cleanupRows.length===1?cleanup.actualDelta:null,fixtureNetDelta:(saleRows.length===1?sale.actualDelta:0)+(cleanupRows.length===1?cleanup.actualDelta:0),
    preflightStock29:freshReadAvailable&&freshStock===29,preflightSaleValid:saleRows.length===1&&sale.stokAwal===30&&sale.stokAkhir===29&&sale.qtyOut===1,preflightCleanupAbsent:cleanupRows.length===0
  };
}

function canonicalSalesS5JasaId_(){const row=JasaRepository.findAll().find(function(item){return String(item[COL_JASA.STATUS]||"").trim().toUpperCase()!=="NONAKTIF";});if(!row)throw new Error("Fixture Jasa aktif S5 tidak tersedia.");return String(row[COL_JASA.ID]||"").trim();}
function canonicalSalesS5StockSnapshot_(){return {stock:Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID)),ledgerRows:StockLedgerRepository.sheet().getLastRow()};}
function canonicalSalesS5Submit_(label,mutate){const p=canonicalSalesS5Fixture_(label);if(mutate)mutate(p);return {payload:p,result:TransactionService.saveTransaction(p)};}
function canonicalSalesS5CleanupDocument_(result,payload){const qty=(payload.items||[]).filter(function(i){return String(i.jenis||i.itemType).toUpperCase()==="BARANG";}).reduce(function(n,i){return n+Number(i.qty||i.quantity||0);},0);if(qty)canonicalSalesS5Cleanup_(result,qty,CANONICAL_SALES_S5_TEST_BARANG_ID);return qty;}
function canonicalSalesS5RunSuccess_(label,runId,mutate,verify){return canonicalSalesS5WithGuard_(label,runId,function(){const before=canonicalSalesS5StockSnapshot_(),run=canonicalSalesS5Submit_(label,mutate),r=run.result;canonicalSalesS5Assert_(r.status===SalesStatus.LUNAS,"Sales tidak LUNAS.");if(verify)verify(run,before);const qty=canonicalSalesS5CleanupDocument_(r,run.payload);canonicalSalesS5Assert_(Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===before.stock,"Cleanup tidak mengembalikan baseline.");return {success:true,salesNumber:r.salesNumber,submissionId:run.payload.submissionId,cleanupQty:qty};});}
function canonicalSalesS5RunReject_(label,mutate,needle){const before=canonicalSalesS5StockSnapshot_(),p=canonicalSalesS5Fixture_(label);mutate(p);let rejected=false;try{TransactionService.saveTransaction(p);}catch(e){rejected=!needle||String(e.message).indexOf(needle)>=0;}canonicalSalesS5Assert_(rejected&&Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===before.stock&&StockLedgerRepository.sheet().getLastRow()===before.ledgerRows,"Rejected Sales melakukan mutasi.");return {success:true,rejected:true};}
function runCanonicalSalesS5JasaOnlyCli(runId){return canonicalSalesS5RunSuccess_("JASA",runId,function(p){p.items=[{jenis:"JASA",kode:canonicalSalesS5JasaId_(),qty:1,harga:1}];},function(run,before){canonicalSalesS5Assert_(Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===before.stock,"Jasa mengubah stok.");const item=PenjualanRepository.findItemsBySalesNumber(run.result.salesNumber)[0];canonicalSalesS5Assert_(item.itemType==="JASA"&&Number(item.unitPrice)!==1,"Harga Jasa tidak authoritative.");});}
function runCanonicalSalesS5MixedCli(runId){return canonicalSalesS5RunSuccess_("MIXED",runId,function(p){p.items.push({jenis:"JASA",kode:canonicalSalesS5JasaId_(),qty:1,harga:1});},function(run){const items=PenjualanRepository.findItemsBySalesNumber(run.result.salesNumber);canonicalSalesS5Assert_(items.length===2&&items[0].itemType!==items[1].itemType,"Mixed persistence tidak lengkap.");});}
function runCanonicalSalesS5DuplicateBarangCli(runId){return canonicalSalesS5RunSuccess_("DUP",runId,function(p){p.items=[{jenis:"BARANG",kode:CANONICAL_SALES_S5_TEST_BARANG_ID,qty:2,harga:1},{jenis:"BARANG",kode:CANONICAL_SALES_S5_TEST_BARANG_ID,qty:3,harga:1}];},function(run,before){const rows=PenjualanRepository.findItemsBySalesNumber(run.result.salesNumber),ledgers=rows.map(function(x){return StockLedgerRepository.findByReferensiFresh(x.lineId);});canonicalSalesS5Assert_(rows.length===2&&rows[0].lineId!==rows[1].lineId&&ledgers.every(function(x){return x.length===1;})&&Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===before.stock-5,"Duplicate Barang tidak line-preserving.");});}
function runCanonicalSalesS5InsufficientStockCli(){return canonicalSalesS5RunReject_("INSUFFICIENT",function(p){p.items[0].qty=Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))+1;},"Stok tidak mencukupi");}
function canonicalSalesS5Conflict_(name,runId,change){return canonicalSalesS5WithGuard_(name,runId,function(){const run=canonicalSalesS5Submit_(name),original=JSON.parse(JSON.stringify(run.payload)),before=canonicalSalesS5StockSnapshot_();change(run.payload);let conflict=false;try{TransactionService.saveTransaction(run.payload);}catch(e){conflict=String(e.message).toLowerCase().indexOf("conflict")>=0;}canonicalSalesS5Assert_(conflict&&Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===before.stock,"Conflict tidak ditolak aman.");canonicalSalesS5CleanupDocument_(run.result,original);canonicalSalesS5Assert_(Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===before.stock,"Conflict cleanup tidak kembali ke baseline.");return {success:true,salesNumber:run.result.salesNumber,conflict:true};});}
function runCanonicalSalesS5ConflictQtyCli(runId){return canonicalSalesS5Conflict_("CONFLICT_QTY",runId,function(p){p.items[0].qty=2;});}
function runCanonicalSalesS5ConflictDiscountCli(runId){return canonicalSalesS5Conflict_("CONFLICT_DISCOUNT",runId,function(p){p.discountValue=1;});}
function runCanonicalSalesS5ConflictPaymentCli(runId){return canonicalSalesS5Conflict_("CONFLICT_PAYMENT",runId,function(p){p.transaksi.bayar=999999998;});}
function runCanonicalSalesS5DifferentSubmissionCli(runId){return canonicalSalesS5WithGuard_("DIFFERENT_SUBMISSION",runId,function(){const a=canonicalSalesS5Submit_("DIFFERENT"),b=canonicalSalesS5Submit_("DIFFERENT");canonicalSalesS5Assert_(a.result.salesNumber!==b.result.salesNumber,"Different submission memakai Sales sama.");canonicalSalesS5CleanupDocument_(a.result,a.payload);canonicalSalesS5CleanupDocument_(b.result,b.payload);return {success:true,first:a.result.salesNumber,second:b.result.salesNumber};});}
function runCanonicalSalesS5DiscountNominalCli(runId){return canonicalSalesS5RunSuccess_("DISC_N",runId,function(p){p.discountType="NOMINAL";p.discountValue=1;},function(run){canonicalSalesS5Assert_(run.result.discount===1&&run.result.total===run.result.subtotal-1,"Discount nominal tidak dihitung server.");});}
function runCanonicalSalesS5DiscountPercentCli(runId){return canonicalSalesS5RunSuccess_("DISC_P",runId,function(p){p.discountType="PERCENT";p.discountValue=10;},function(run){canonicalSalesS5Assert_(run.result.discount===Math.round(run.result.subtotal*.1)&&run.result.total===run.result.subtotal-run.result.discount,"Discount percent tidak dihitung server.");});}
function runCanonicalSalesS5DiscountOverSubtotalCli(){return canonicalSalesS5RunReject_("DISC_OVER",function(p){p.discountType="NOMINAL";p.discountValue=999999999;},"Discount tidak boleh melebihi subtotal");}
function runCanonicalSalesS5DiscountOverPercentCli(){return canonicalSalesS5RunReject_("DISC_PERCENT_OVER",function(p){p.discountType="PERCENT";p.discountValue=101;},"Discount percent");}
function runCanonicalSalesS5CashInsufficientCli(){return canonicalSalesS5RunReject_("CASH_LOW",function(p){p.transaksi.bayar=0;},"Pembayaran TUNAI");}
function runCanonicalSalesS5DiscountNegativeCli(){return canonicalSalesS5RunReject_("DISC_NEG",function(p){p.discountType="NOMINAL";p.discountValue=-1;},"Discount harus");}
function canonicalSalesS5InventoryRollback_(runId,failIndex){return canonicalSalesS5WithGuard_("INVENTORY_LEDGER_ROLLBACK_"+failIndex,runId,function(){const before=canonicalSalesS5StockSnapshot_(),p=canonicalSalesS5Fixture_("ROLLBACK");p.items=[{jenis:"BARANG",kode:CANONICAL_SALES_S5_TEST_BARANG_ID,qty:1,harga:1},{jenis:"BARANG",kode:CANONICAL_SALES_S5_TEST_BARANG_ID,qty:1,harga:1}];CanonicalSalesInventoryService.setTestHooksForTest_({beforeLedgerWrite:function(line,index){if(index===failIndex)throw new Error("S5_TEST_LEDGER_FAILURE");}});let failed=false;try{TransactionService.saveTransaction(p);}catch(e){failed=String(e.message).indexOf("S5_TEST_LEDGER_FAILURE")>=0;}finally{CanonicalSalesInventoryService.setTestHooksForTest_(null);}canonicalSalesS5Assert_(failed&&Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID))===before.stock&&StockLedgerRepository.sheet().getLastRow()===before.ledgerRows,"Inventory rollback gagal.");return {success:true,submissionId:p.submissionId,fixtureNet:0};});}
function runCanonicalSalesS5InventoryFirstLineRollbackCli(runId){return canonicalSalesS5InventoryRollback_(runId,0);}
function runCanonicalSalesS5InventorySecondLineRollbackCli(runId){return canonicalSalesS5InventoryRollback_(runId,1);}
function runCanonicalSalesS5ReceiptCli(runId){return canonicalSalesS5WithGuard_("RECEIPT",runId,function(){const run=canonicalSalesS5Submit_("RECEIPT"),data=getDataStruk(run.result.salesNumber);canonicalSalesS5Assert_(data&&data.noTransaksi===run.result.salesNumber,"Receipt canonical Sales tidak terbaca.");canonicalSalesS5CleanupDocument_(run.result,run.payload);return {success:true,salesNumber:run.result.salesNumber,submissionId:run.payload.submissionId};});}
function runCanonicalSalesS5QrisCli(runId){return canonicalSalesS5RunSuccess_("QRIS",runId,function(p){p.transaksi.metodeBayar="QRIS";p.transaksi.bayar=1;},function(run){const sh=PenjualanRepository.getHeaderSheet(),c=PenjualanRepository.getColumnMap_(sh),row=sh.getDataRange().getValues().slice(1).find(function(x){return String(x[c.NoTransaksi])===run.result.salesNumber;});canonicalSalesS5Assert_(row&&String(row[c.MetodeBayar])==="QRIS"&&Number(row[c.Bayar])===Number(row[c.GrandTotal])&&Number(row[c.Kembalian])===0&&String(row[c.Status])===SalesStatus.LUNAS,"QRIS persistence tidak dinormalisasi.");});}
function runCanonicalSalesS5HistoricalCli(){return runCanonicalSalesS4HistoricalCli();}

function canonicalSalesS5ActiveKey_(){return "CANONICAL_SALES:S5:ACTIVE_RUN";}
function canonicalSalesS5RunKey_(runId){return "CANONICAL_SALES:S5:RUN:"+runId;}
function canonicalSalesS5FreshPair_(){return {normal:Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID)),fresh:canonicalSalesS5FreshStock_(CANONICAL_SALES_S5_TEST_BARANG_ID)};}
function getCanonicalSalesS5ActiveRunCli(){const raw=PropertiesService.getScriptProperties().getProperty(canonicalSalesS5ActiveKey_());return raw?JSON.parse(raw):{state:"IDLE"};}
function getCanonicalSalesS5RunStatusCli(runId){const raw=PropertiesService.getScriptProperties().getProperty(canonicalSalesS5RunKey_(String(runId||"")));if(!raw)return {runId:String(runId||""),state:"NOT_RUN"};const value=JSON.parse(raw),result=value.result||{};return {runId:value.runId,scenario:value.scenario,state:value.status,startedAt:value.startedAt,finishedAt:value.finishedAt,submissionId:result.submissionId||"",salesNumber:result.salesNumber||"",barangId:value.barangId||"",baseline:value.baseline||null,finalNormalStock:value.finalStock&&value.finalStock.normal,finalFreshStock:value.finalStock&&value.finalStock.fresh,fixtureNet:value.fixtureNet,error:value.error||""};}
function canStartCanonicalSalesS5Run(){const active=getCanonicalSalesS5ActiveRunCli();return {canStart:active.state!=="RUNNING",activeRun:active};}
function canonicalSalesS5WithGuard_(scenario,runId,fn){
  runId=String(runId||"").trim();if(!runId)throw new Error("S5 runId wajib diisi.");const store=PropertiesService.getScriptProperties(),lock=LockService.getScriptLock(),activeKey=canonicalSalesS5ActiveKey_(),statusKey=canonicalSalesS5RunKey_(runId),startedAt=new Date();
  lock.waitLock(30000);try{const raw=store.getProperty(activeKey),active=raw?JSON.parse(raw):null;if(active&&active.state==="RUNNING")throw new Error("S5_ACTIVE_RUN: "+active.runId+" / "+active.scenario);const baseline=canonicalSalesS5FreshPair_();if(baseline.normal!==30||baseline.fresh!==30)throw new Error("DIRTY_TEST_FIXTURE: BRG000097 normal="+baseline.normal+", fresh="+baseline.fresh);store.setProperty(activeKey,JSON.stringify({runId:runId,scenario:scenario,startedAt:startedAt.toISOString(),state:"RUNNING"}));store.setProperty(statusKey,JSON.stringify({runId:runId,scenario:scenario,status:"RUNNING",barangId:CANONICAL_SALES_S5_TEST_BARANG_ID,baseline:baseline,startedAt:startedAt.toISOString()}));}finally{lock.releaseLock();}
  try{const result=fn(),finalStock=canonicalSalesS5FreshPair_();canonicalSalesS5Assert_(finalStock.normal===30&&finalStock.fresh===30,"Final baseline BRG000097 tidak kembali ke 30.");const status={runId:runId,scenario:scenario,status:"PASS",barangId:CANONICAL_SALES_S5_TEST_BARANG_ID,result:result,finalStock:finalStock,fixtureNet:0,startedAt:startedAt.toISOString(),finishedAt:new Date().toISOString()};store.setProperty(statusKey,JSON.stringify(status));return Object.assign({},result,{runId:runId});}catch(error){const status={runId:runId,scenario:scenario,status:"FAIL",barangId:CANONICAL_SALES_S5_TEST_BARANG_ID,error:String(error.message||error),finalStock:canonicalSalesS5FreshPair_(),startedAt:startedAt.toISOString(),finishedAt:new Date().toISOString()};store.setProperty(statusKey,JSON.stringify(status));throw error;}finally{lock.waitLock(30000);try{const raw=store.getProperty(activeKey),active=raw?JSON.parse(raw):null;if(active&&active.runId===runId)store.deleteProperty(activeKey);}finally{lock.releaseLock();}}
}
function runCanonicalSalesS5DirectCli(runId){return canonicalSalesS5WithGuard_("DIRECT",runId,canonicalSalesS5DirectUnsafe_);}
function runCanonicalSalesS5RetryCli(runId){return canonicalSalesS5WithGuard_("RETRY",runId,canonicalSalesS5RetryUnsafe_);}
function runCanonicalSalesS5FinalizationRecoveryCli(runId){return canonicalSalesS5WithGuard_("FINALIZATION_RECOVERY",runId,canonicalSalesS5FinalizationRecoveryUnsafe_);}

function auditCanonicalSalesS5SO0048SO0049FlatCli(){
  const barangId="BRG000097",numbers=["SO2608220048","SO2608220049"],headers=PenjualanRepository.getHeaderSheet(),columns=PenjualanRepository.getColumnMap_(headers),headerRows=headers.getDataRange().getValues().slice(1),all=StockLedgerRepository.sheet().getDataRange().getValues().slice(1);
  const flat=function(row){if(!row)return null;const before=Number(row[COL_STOK.STOKAWAL]),after=Number(row[COL_STOK.STOKAKHIR]);return {ledgerId:String(row[COL_STOK.ID]||""),movementType:String(row[COL_STOK.JENISMUTASI]||""),reference:String(row[COL_STOK.REFERENSI]||""),qtyIn:Number(row[COL_STOK.QTYMASUK]||0),qtyOut:Number(row[COL_STOK.QTYKELUAR]||0),stokAwal:before,stokAkhir:after,actualDelta:after-before,createdAt:String(row[COL_STOK.CREATEDAT]||"")};};
  const fixtures=numbers.map(function(number){const header=headerRows.find(function(row){return String(row[columns.NoTransaksi]||"")===number;}),details=PenjualanRepository.findItemsBySalesNumber(number),sale=StockLedgerRepository.findByReferensiFresh(number+":L001"),cleanup=StockLedgerRepository.findByReferensiFresh("S5_TEST_CLEANUP:"+number);return {salesNumber:number,submissionId:header?String(header[columns.SubmissionId]||""):"",status:header?String(header[columns.Status]||""):"",createdAt:header?String(header[columns.CreatedAt]||""):"",barangId:details[0]?String(details[0].itemId||""):"",qty:details[0]?Number(details[0].quantity||0):null,lineId:details[0]?String(details[0].lineId||""):"",saleCount:sale.length,cleanupCount:cleanup.length,sale:flat(sale[0]),cleanup:flat(cleanup[0]),net:(sale.length===1?flat(sale[0]).actualDelta:0)+(cleanup.length===1?flat(cleanup[0]).actualDelta:0)};});
  const start=all.findIndex(function(row){return String(row[COL_STOK.ID]||"")==="STK2608220082";}),end=all.findIndex(function(row){return String(row[COL_STOK.ID]||"")==="STK2608220085";}),trace=all.slice(Math.max(0,start-1),end+1).filter(function(row){return String(row[COL_STOK.BARANG_ID]||"")===barangId;}).map(flat),source=trace[0]||null;
  const active=SpreadsheetApp.getActiveSpreadsheet(),fresh=SpreadsheetApp.openById(active.getId()),stockOf=function(id){const row=fresh.getSheetByName(CONFIG.SHEET.BARANG).getDataRange().getValues().slice(1).find(function(item){return String(item[COL_BARANG.ID]||"")===id;});return row?Number(row[COL_BARANG.STOK]):null;};
  return {success:true,fixturesJson:JSON.stringify(fixtures),traceJson:JSON.stringify(trace),preSO0048MovementJson:JSON.stringify(source),normalBRG000097:Number(BarangRepository.getStock(barangId)),freshBRG000097:stockOf(barangId),freshBRG000001:stockOf("BRG000001")};
}
function auditCanonicalSalesS5IsolationRepairPlanCli(){const ref="S5_TEST_REPAIR:BRG000097:ISOLATION_OVERLAP_20260822",rows=StockLedgerRepository.findByReferensiFresh(ref),fresh=canonicalSalesS5FreshStock_(CANONICAL_SALES_S5_TEST_BARANG_ID);return {success:true,barangId:CANONICAL_SALES_S5_TEST_BARANG_ID,currentNormal:Number(BarangRepository.getStock(CANONICAL_SALES_S5_TEST_BARANG_ID)),currentFresh:fresh,cleanBaseline:30,pendingDelta:fresh-30,proposedMovementType:MovementType.SALE,proposedQty:1,proposedReference:ref,existingRepairReferenceCount:rows.length,expectedAfterRepair:fresh-1};}
function runCanonicalSalesS5ApprovedIsolationRepairCli(){const ref="S5_TEST_REPAIR:BRG000097:ISOLATION_OVERLAP_20260822",plan=auditCanonicalSalesS5IsolationRepairPlanCli(),active=getCanonicalSalesS5ActiveRunCli(),brg001=canonicalSalesS5FreshStock_("BRG000001");if(active.state!=="IDLE"||plan.currentNormal!==31||plan.currentFresh!==31||brg001!==66||plan.existingRepairReferenceCount!==0)throw new Error("S5.3D repair preflight tidak sesuai.");InventoryService.moveStock({kodeBarang:CANONICAL_SALES_S5_TEST_BARANG_ID,movementType:MovementType.SALE,qty:1,reference:ref,note:"Test isolation overlap repair; non-production; historical ledger preserved.",performedBy:"S5_TEST"});const rows=StockLedgerRepository.findByReferensiFresh(ref),after=canonicalSalesS5FreshPair_();if(rows.length!==1||Number(rows[0][COL_STOK.QTYKELUAR])!==1||Number(rows[0][COL_STOK.STOKAWAL])!==31||Number(rows[0][COL_STOK.STOKAKHIR])!==30||after.normal!==30||after.fresh!==30||canonicalSalesS5FreshStock_("BRG000001")!==66)throw new Error("S5.3D repair verification gagal.");return {success:true,repairLedgerId:String(rows[0][COL_STOK.ID]||""),stockBefore:31,stockAfter:30,reference:ref};}
function auditCanonicalSalesS5QrisFailureCli(){const hs=PenjualanRepository.getHeaderSheet(),c=PenjualanRepository.getColumnMap_(hs),h=hs.getDataRange().getValues().slice(1).filter(function(r){return String(r[c.SubmissionId]||"").indexOf("S5-QRIS-")===0;}).pop();if(!h)return {found:false};const n=String(h[c.NoTransaksi]),items=PenjualanRepository.findItemsBySalesNumber(n),line=items[0],sale=StockLedgerRepository.findByReferensiFresh(line.lineId),cleanup=StockLedgerRepository.findByReferensiFresh("S5_TEST_CLEANUP:"+n),row=sale[0],fresh=canonicalSalesS5FreshPair_();return {found:true,submissionId:String(h[c.SubmissionId]),salesNumber:n,transactionId:String(h[c.TransactionId]),status:String(h[c.Status]),barangId:line.itemId,qty:Number(line.quantity),subtotal:Number(h[c.Subtotal]),discount:Number(h[c.DiskonNota]),total:Number(h[c.GrandTotal]),paymentMethod:String(h[c.MetodeBayar]),amountPaid:Number(h[c.Bayar]),change:Number(h[c.Kembalian]),detailCount:items.length,headerCount:PenjualanRepository.findAllBySubmissionId(h[c.SubmissionId]).length,saleCount:sale.length,saleLedgerId:row?String(row[COL_STOK.ID]):"",saleQtyOut:row?Number(row[COL_STOK.QTYKELUAR]):0,saleStokAwal:row?Number(row[COL_STOK.STOKAWAL]):null,saleStokAkhir:row?Number(row[COL_STOK.STOKAKHIR]):null,cleanupCount:cleanup.length,normalBRG000097:fresh.normal,freshBRG000097:fresh.fresh,normalBRG000001:Number(BarangRepository.getStock("BRG000001")),freshBRG000001:canonicalSalesS5FreshStock_("BRG000001")};}
function runCanonicalSalesS5Qris0055CleanupCli(){const a=auditCanonicalSalesS5QrisFailureCli(),ref="S5_TEST_CLEANUP:"+a.salesNumber;if(!a.found||getCanonicalSalesS5ActiveRunCli().state!=="IDLE"||a.salesNumber!=="SO2608220055"||a.saleCount!==1||a.saleQtyOut!==1||a.saleStokAwal!==30||a.saleStokAkhir!==29||a.cleanupCount!==0||a.normalBRG000097!==29||a.freshBRG000097!==29||a.normalBRG000001!==66||a.freshBRG000001!==66)throw new Error("S5.4E QRIS cleanup preflight tidak sesuai.");InventoryService.moveStock({kodeBarang:"BRG000097",movementType:MovementType.PURCHASE,qty:1,reference:ref,note:"Canonical Sales S5 QRIS failed-run compensating stock IN",performedBy:"S5_TEST"});const after=auditCanonicalSalesS5QrisFailureCli();if(after.cleanupCount!==1||after.normalBRG000097!==30||after.freshBRG000097!==30||after.normalBRG000001!==66||after.freshBRG000001!==66)throw new Error("S5.4E QRIS cleanup verification gagal.");return {success:true,salesNumber:a.salesNumber,reference:ref};}
function runCanonicalSalesS5ParallelWorkerCli(workerId,submissionId,quantity){
  const p=canonicalSalesS5Fixture_("PARALLEL");
  p.submissionId=String(submissionId);p.items[0].qty=Number(quantity);p.transaksi.bayar=999999;
  const startedAt=new Date().toISOString();
  try{
    const result=TransactionService.saveTransaction(p);
    return {workerId:String(workerId),startedAt:startedAt,finishedAt:new Date().toISOString(),submissionId:p.submissionId,requestedQty:Number(quantity),success:true,salesNumber:String(result.salesNumber||""),alreadyPrepared:!!result.alreadyPrepared,alreadyRecorded:!!result.alreadyRecorded,status:String(result.status||""),error:""};
  }catch(error){
    return {workerId:String(workerId),startedAt:startedAt,finishedAt:new Date().toISOString(),submissionId:p.submissionId,requestedQty:Number(quantity),success:false,salesNumber:"",alreadyPrepared:false,alreadyRecorded:false,status:"",error:String(error.message||error)};
  }
}
function canonicalSalesS5ParallelLedger_(lineId){
  return StockLedgerRepository.findByReferensiFresh(lineId).map(function(row){return {ledgerId:String(row[COL_STOK.ID]||""),movementType:String(row[COL_STOK.JENISMUTASI]||""),reference:String(row[COL_STOK.REFERENSI]||""),qtyOut:Number(row[COL_STOK.QTYKELUAR]||0),stokAwal:Number(row[COL_STOK.STOKAWAL]),stokAkhir:Number(row[COL_STOK.STOKAKHIR]),timestamp:String(row[COL_STOK.CREATEDAT]||"")};});
}
function inspectCanonicalSalesS5ParallelCli(submissionIds){
  const ids=(Array.isArray(submissionIds)?submissionIds:String(submissionIds||"").split("|")).map(String).filter(Boolean),documents=ids.map(function(submissionId){
    const headers=PenjualanRepository.findAllBySubmissionId(submissionId),header=headers[0]||null,details=header?PenjualanRepository.findItemsBySalesNumber(header.salesNumber):[],ledgers=details.reduce(function(all,detail){return all.concat(canonicalSalesS5ParallelLedger_(detail.lineId));},[]);
    return {submissionId:submissionId,headerCount:headers.length,salesNumber:header?String(header.salesNumber||""):"",status:header?String(header.status||""):"",transactionId:header?String(header.transactionId||""):"",detailCount:details.length,lineIds:details.map(function(detail){return String(detail.lineId||"");}),detailQty:details.reduce(function(total,detail){return total+Number(detail.quantity||0);},0),ledgerCount:ledgers.length,ledgerIds:ledgers.map(function(ledger){return ledger.ledgerId;}),qtyOut:ledgers.reduce(function(total,ledger){return total+ledger.qtyOut;},0),ledgerJson:JSON.stringify(ledgers)};
  });
  const pair=canonicalSalesS5FreshPair_();
  return {success:true,documentsJson:JSON.stringify(documents),documentCount:documents.length,totalHeaderCount:documents.reduce(function(total,item){return total+item.headerCount;},0),totalDetailCount:documents.reduce(function(total,item){return total+item.detailCount;},0),totalLedgerCount:documents.reduce(function(total,item){return total+item.ledgerCount;},0),totalQtyOut:documents.reduce(function(total,item){return total+item.qtyOut;},0),normalBRG000097:pair.normal,freshBRG000097:pair.fresh,normalBRG000001:Number(BarangRepository.getStock("BRG000001")),freshBRG000001:canonicalSalesS5FreshStock_("BRG000001")};
}
function runCanonicalSalesS5ParallelCleanupCli(submissionId,reference,expectedFinalStock){
  const headers=PenjualanRepository.findAllBySubmissionId(String(submissionId)),pair=canonicalSalesS5FreshPair_();
  canonicalSalesS5Assert_(headers.length===1&&pair.normal===pair.fresh&&canonicalSalesS5FreshStock_("BRG000001")===66,"Parallel cleanup preflight tidak aman.");
  const details=PenjualanRepository.findItemsBySalesNumber(headers[0].salesNumber),ledgers=details.reduce(function(all,detail){return all.concat(canonicalSalesS5ParallelLedger_(detail.lineId));},[]),qty=ledgers.reduce(function(total,ledger){return total+ledger.qtyOut;},0),ref=String(reference||"");
  canonicalSalesS5Assert_(headers[0].status===SalesStatus.LUNAS&&details.length===1&&ledgers.length===1&&qty>0&&StockLedgerRepository.findByReferensiFresh(ref).length===0,"Parallel cleanup evidence tidak valid.");
  InventoryService.moveStock({kodeBarang:CANONICAL_SALES_S5_TEST_BARANG_ID,movementType:MovementType.PURCHASE,qty:qty,reference:ref,note:"Canonical Sales S5.5 true-parallel compensating stock IN",performedBy:"S5_TEST"});
  const expected=expectedFinalStock===undefined||expectedFinalStock===null?30:Number(expectedFinalStock),cleanup=StockLedgerRepository.findByReferensiFresh(ref),after=canonicalSalesS5FreshPair_();
  canonicalSalesS5Assert_(cleanup.length===1&&Number(cleanup[0][COL_STOK.QTYMASUK]||0)===qty&&after.normal===expected&&after.fresh===expected&&canonicalSalesS5FreshStock_("BRG000001")===66,"Parallel cleanup tidak mencapai stok target.");
  return {success:true,submissionId:String(submissionId),salesNumber:String(headers[0].salesNumber),qty:qty,cleanupReference:ref,cleanupLedgerId:String(cleanup[0][COL_STOK.ID]||""),normalBRG000097:after.normal,freshBRG000097:after.fresh,normalBRG000001:Number(BarangRepository.getStock("BRG000001")),freshBRG000001:canonicalSalesS5FreshStock_("BRG000001")};
}
