/** Runtime smoke for S6.3 preparation. It persists only DRAFT Sales metadata. */
function canonicalWoSettlementPreparationAssert_(condition,message){if(!condition)throw new Error(message);}
function canonicalWoS63Run_(runId,scenario,fn){const store=PropertiesService.getScriptProperties(),key="CANONICAL_WO_SETTLEMENT:S6.3:RUN:"+String(runId||"").trim(),activeKey="CANONICAL_WO_SETTLEMENT:S6.3:ACTIVE_RUN",lock=LockService.getScriptLock();if(!runId)throw new Error("runId wajib diisi.");lock.waitLock(30000);try{const active=store.getProperty(activeKey);if(active)throw new Error("S6.3 ACTIVE_RUN");store.setProperty(activeKey,JSON.stringify({runId:runId,scenario:scenario,state:"RUNNING",startedAt:new Date().toISOString()}));store.setProperty(key,JSON.stringify({runId:runId,scenario:scenario,state:"RUNNING",startedAt:new Date().toISOString()}));}finally{lock.releaseLock();}try{const result=fn();store.setProperty(key,JSON.stringify(Object.assign({runId:runId,scenario:scenario,state:"PASS",finishedAt:new Date().toISOString()},result)));return result;}catch(error){store.setProperty(key,JSON.stringify({runId:runId,scenario:scenario,state:"FAIL",error:String(error.message||error),finishedAt:new Date().toISOString()}));throw error;}finally{lock.waitLock(30000);try{const raw=store.getProperty(activeKey),active=raw?JSON.parse(raw):null;if(active&&active.runId===runId)store.deleteProperty(activeKey);}finally{lock.releaseLock();}}}
function runCanonicalWorkOrderSettlementExistingAnomalyCli(runId){return canonicalWoS63Run_(runId,"EXISTING_DUPLICATE_ANOMALY",function(){const before=PenjualanRepository.findSettlementSalesByWorkOrder("WO2608140015").length;let blocked=false;try{prepareCanonicalWorkOrderSettlement({workOrderId:"WO2608140015",submissionId:"S6-3-ANOMALY-GUARD",directSaleItems:[{jenis:"BARANG",kode:"BRG000097",qty:1}]});}catch(error){blocked=String(error.message).indexOf("AUDIT_ANOMALY")>=0;}canonicalWoSettlementPreparationAssert_(blocked&&PenjualanRepository.findSettlementSalesByWorkOrder("WO2608140015").length===before,"Anomali existing tidak diblokir aman.");return {workOrderId:"WO2608140015",salesCount:before,blocked:true};});}
function runCanonicalWorkOrderSettlementNewResumeCli(runId){return canonicalWoS63Run_(runId,"NEW_AND_RESUME",function(){return runCanonicalWorkOrderSettlementPreparationSmokeCli();});}
function canonicalWoS63FixtureInput_(submissionId){return {workOrderId:"WO2608200012",submissionId:submissionId,directSaleItems:[{jenis:"BARANG",kode:"BRG000097",qty:1}],discountType:"NOMINAL",discountValue:0,paymentIntent:{}};}
function canonicalWoS63NoInventory_(before){canonicalWoSettlementPreparationAssert_(BarangRepository.getStock("BRG000097")===before.stock&&StockLedgerRepository.sheet().getLastRow()===before.ledger,"Preparation mengubah inventory.");}
function runCanonicalWorkOrderSettlementSamePayloadResumeCli(runId){return canonicalWoS63Run_(runId,"SAME_PAYLOAD_RESUME",function(){const before={stock:BarangRepository.getStock("BRG000097"),ledger:StockLedgerRepository.sheet().getLastRow()},count=PenjualanRepository.findSettlementSalesByWorkOrder("WO2608200012").length,result=prepareCanonicalWorkOrderSettlement(canonicalWoS63FixtureInput_("S6-3-SAME-"+runId));canonicalWoSettlementPreparationAssert_(result.state==="RESUMED"&&result.salesNumber==="SO2608220068"&&PenjualanRepository.findSettlementSalesByWorkOrder("WO2608200012").length===count,"Same payload tidak resume.");canonicalWoS63NoInventory_(before);return {salesNumber:result.salesNumber,state:result.state,salesCount:count};});}
function runCanonicalWorkOrderSettlementDifferentSubmissionResumeCli(runId){return canonicalWoS63Run_(runId,"DIFFERENT_SUBMISSION_RESUME",function(){const before={stock:BarangRepository.getStock("BRG000097"),ledger:StockLedgerRepository.sheet().getLastRow()},count=PenjualanRepository.findSettlementSalesByWorkOrder("WO2608200012").length,result=prepareCanonicalWorkOrderSettlement(canonicalWoS63FixtureInput_("S6-3-DIFFERENT-"+runId));canonicalWoSettlementPreparationAssert_(result.state==="RESUMED"&&result.salesNumber==="SO2608220068"&&PenjualanRepository.findSettlementSalesByWorkOrder("WO2608200012").length===count,"Different submission tidak resume.");canonicalWoS63NoInventory_(before);return {salesNumber:result.salesNumber,state:result.state,salesCount:count};});}
function runCanonicalWorkOrderSettlementChangedPayloadConflictCli(runId){return canonicalWoS63Run_(runId,"CHANGED_PAYLOAD_CONFLICT",function(){const before={stock:BarangRepository.getStock("BRG000097"),ledger:StockLedgerRepository.sheet().getLastRow()},count=PenjualanRepository.findSettlementSalesByWorkOrder("WO2608200012").length,input=canonicalWoS63FixtureInput_("S6-3-CONFLICT-"+runId);input.discountValue=1;let conflict=false;try{prepareCanonicalWorkOrderSettlement(input);}catch(e){conflict=String(e.message).indexOf("SETTLEMENT_CONFLICT")>=0;}canonicalWoSettlementPreparationAssert_(conflict&&PenjualanRepository.findSettlementSalesByWorkOrder("WO2608200012").length===count,"Changed payload tidak conflict.");canonicalWoS63NoInventory_(before);return {conflict:true,salesCount:count};});}
function runCanonicalWorkOrderSettlementParallelWorkerCli(workerId,workOrderId,submissionId,discountValue){const startedAt=new Date().toISOString();try{const result=prepareCanonicalWorkOrderSettlement({workOrderId:String(workOrderId),submissionId:String(submissionId),directSaleItems:[{jenis:"BARANG",kode:"BRG000097",qty:1}],discountType:"NOMINAL",discountValue:Number(discountValue)||0,paymentIntent:{}});return {workerId:String(workerId),startedAt:startedAt,finishedAt:new Date().toISOString(),success:true,state:result.state,salesNumber:result.salesNumber,error:""};}catch(e){return {workerId:String(workerId),startedAt:startedAt,finishedAt:new Date().toISOString(),success:false,state:"",salesNumber:"",error:String(e.message||e)};}}
function runCanonicalWorkOrderSettlementPreparationSmokeCli(){
  const sheet=WorkOrderRepository.sheet(), headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0], idCol=headers.indexOf("ID"), statusCol=headers.indexOf("Status"), rows=sheet.getDataRange().getValues().slice(1);
  const workOrderId=rows.map(function(row){return {id:String(row[idCol]||""),status:String(row[statusCol]||"")};}).filter(function(row){return row.id&&row.status===WorkOrderStatus.SELESAI&&PenjualanRepository.findSettlementSalesByWorkOrder(row.id).length===0;}).map(function(row){try{return planCanonicalWorkOrderSettlement({workOrderId:row.id,directSaleItems:[{jenis:"BARANG",kode:"BRG000097",qty:1}] }).eligible?row.id:"";}catch(e){return "";}}).filter(Boolean)[0];
  if(!workOrderId)throw new Error("Fixture Work Order SELESAI yang eligible tidak tersedia.");
  const before={stock:BarangRepository.getStock("BRG000097"),ledger:StockLedgerRepository.sheet().getLastRow(),wop:getSheet_(CONFIG.SHEET.WORK_ORDER_PART).getLastRow(),purchase:PurchaseRepository.getHeaderSheet().getLastRow()};
  const input={workOrderId:workOrderId,submissionId:"S6-3-SMOKE-"+new Date().getTime(),directSaleItems:[{jenis:"BARANG",kode:"BRG000097",qty:1}],discountType:"NOMINAL",discountValue:0,paymentIntent:{}};
  const first=prepareCanonicalWorkOrderSettlement(input), retry=prepareCanonicalWorkOrderSettlement(Object.assign({},input,{submissionId:input.submissionId+"-RETRY"})), details=PenjualanRepository.findItemsBySalesNumber(first.salesNumber), metadata=WorkOrderRepository.getSettlementMetadata(workOrderId), after={stock:BarangRepository.getStock("BRG000097"),ledger:StockLedgerRepository.sheet().getLastRow(),wop:getSheet_(CONFIG.SHEET.WORK_ORDER_PART).getLastRow(),purchase:PurchaseRepository.getHeaderSheet().getLastRow()};
  canonicalWoSettlementPreparationAssert_(first.state==="PREPARED"&&retry.state==="RESUMED"&&first.salesNumber===retry.salesNumber,"Resume settlement tidak memakai Sales yang sama.");
  canonicalWoSettlementPreparationAssert_(metadata.settlementStatus==="UNSETTLED"&&metadata.settlementSalesNumber===first.salesNumber,"Relation Work Order preparation tidak tersimpan aman.");
  canonicalWoSettlementPreparationAssert_(details.some(function(item){return item.sourceDocumentType==="DIRECT_SALE"&&item.sourceDocumentId===first.salesNumber;}),"Trace direct sale tidak tersimpan.");
  canonicalWoSettlementPreparationAssert_(JSON.stringify(before)===JSON.stringify(after),"Preparation mengubah inventory/WOP/Purchase.");
  return {success:true,workOrderId:workOrderId,salesNumber:first.salesNumber,state:first.state,resume:retry.state,settlementStatus:metadata.settlementStatus,detailCount:details.length};
}
