function canonicalPurchaseP5BAssert_(condition, message){ if(!condition){ throw new Error("Canonical Purchase P5B gagal: " + message); } }
function canonicalPurchaseP5BBarang_(count){ const ids=BarangRepository.findAll().map(function(row){return String(row[COL_BARANG.ID]||"").trim();}).filter(Boolean); if(ids.length<count)throw new Error("Fixture Barang P5B tidak mencukupi.");return ids.slice(0,count); }
function canonicalPurchaseP5BPayload_(label, items){ const token="P5B-"+label+"-"+Date.now();return {submissionId:token,supplier:"P5B_TEST",noFaktur:token,admin:"P5B_TEST",keterangan:"Canonical production test",items:items}; }
function canonicalPurchaseP5BSnapshot_(barangIds){return {headers:PurchaseRepository.getHeaderSheet().getLastRow(),details:PurchaseRepository.getDetailSheet().getLastRow(),ledger:StockLedgerRepository.sheet().getLastRow(),stocks:barangIds.map(function(id){return BarangRepository.getStock(id);})};}
function canonicalPurchaseP5BCleanup_(purchaseNumber, items){items.forEach(function(item){InventoryService.moveStock({kodeBarang:item.kodeBarang,movementType:MovementType.SALE,qty:Number(item.qty),reference:"P5B_TEST_CLEANUP:"+purchaseNumber,note:"Canonical Purchase P5B stock cleanup",performedBy:"P5B_TEST"});});}
function runCanonicalPurchaseP5BProductionRegressionCli(){
    const barang=canonicalPurchaseP5BBarang_(2), oneItems=[{kodeBarang:barang[0],qty:2,hargaBeli:10000}], before=canonicalPurchaseP5BSnapshot_([barang[0]]), payload=canonicalPurchaseP5BPayload_("RETRY",oneItems), first=submitPurchase(payload), retry=submitPurchase(payload), after=canonicalPurchaseP5BSnapshot_([barang[0]]);
    canonicalPurchaseP5BAssert_(first.status===PurchaseStatus.POSTED&&retry.status===PurchaseStatus.POSTED&&retry.alreadyRecorded===true,"retry canonical tidak POSTED/alreadyRecorded.");
    canonicalPurchaseP5BAssert_(first.purchaseNumber===retry.purchaseNumber&&after.headers===before.headers+1&&after.details===before.details+1&&after.ledger===before.ledger+1&&after.stocks[0]===before.stocks[0]+2,"retry membuat mutasi/persistensi tambahan.");
    const record=PurchaseRepository.findByPurchaseNumber(first.purchaseNumber); canonicalPurchaseP5BAssert_(record.status===PurchaseStatus.POSTED&&record.submissionId===payload.submissionId,"metadata/status canonical tidak tersimpan.");
    const conflictSnapshot=canonicalPurchaseP5BSnapshot_([barang[0]]); payload.items[0].qty=9; let conflict=false;try{submitPurchase(payload);}catch(error){conflict=String(error.message).indexOf("conflict")>=0;}const conflictAfter=canonicalPurchaseP5BSnapshot_([barang[0]]);
    canonicalPurchaseP5BAssert_(conflict&&JSON.stringify(conflictSnapshot)===JSON.stringify(conflictAfter),"Conflict qty mengubah Purchase/inventory.");
    canonicalPurchaseP5BCleanup_(first.purchaseNumber,oneItems);
    const duplicateItems=[{kodeBarang:barang[0],qty:3,hargaBeli:10000},{kodeBarang:barang[0],qty:2,hargaBeli:10000}], duplicateBefore=canonicalPurchaseP5BSnapshot_([barang[0]]), duplicate=submitPurchase(canonicalPurchaseP5BPayload_("DUP",duplicateItems)), duplicateDetails=PurchaseRepository.findItemsByPurchaseNumber(duplicate.purchaseNumber), duplicateLedgers=duplicate.ledgerIds;
    canonicalPurchaseP5BAssert_(duplicateDetails.length===2&&duplicateDetails[0].lineId===duplicate.purchaseNumber+":L001"&&duplicateDetails[1].lineId===duplicate.purchaseNumber+":L002"&&duplicateLedgers.length===2&&BarangRepository.getStock(barang[0])===duplicateBefore.stocks[0]+5,"Duplicate Barang tidak line-preserving.");
    canonicalPurchaseP5BCleanup_(duplicate.purchaseNumber,duplicateItems);
    return {success:true,test:"CANONICAL_PURCHASE_P5B_PRODUCTION",message:"PASS",purchaseNumbers:[first.purchaseNumber,duplicate.purchaseNumber]};
}
function runCanonicalPurchaseP5BFinalizationRecoveryCli(){
    const barang=canonicalPurchaseP5BBarang_(1)[0],items=[{kodeBarang:barang,qty:1,hargaBeli:10000}],before=canonicalPurchaseP5BSnapshot_([barang]),payload=canonicalPurchaseP5BPayload_("FINALIZE",items);let failed=false;
    PurchaseService.setTestHooksForTest_({beforeStatusUpdate:function(number,status){if(status===PurchaseStatus.POSTED)throw new Error("P5B forced finalization failure");}});
    try{submitPurchase(payload);}catch(error){failed=String(error.message).indexOf("committed")>=0;}finally{PurchaseService.setTestHooksForTest_(null);}
    const pending=PurchaseRepository.findBySubmissionId(payload.submissionId);canonicalPurchaseP5BAssert_(failed&&pending.status===PurchaseStatus.POSTING&&BarangRepository.getStock(barang)===before.stocks[0]+1,"Finalization failure tidak mempertahankan committed evidence.");
    const retry=submitPurchase(payload),after=canonicalPurchaseP5BSnapshot_([barang]);canonicalPurchaseP5BAssert_(retry.status===PurchaseStatus.POSTED&&retry.alreadyRecorded&&after.ledger===before.ledger+1&&after.stocks[0]===before.stocks[0]+1,"Retry finalization membuat mutasi kedua.");
    canonicalPurchaseP5BCleanup_(retry.purchaseNumber,items);return {success:true,test:"CANONICAL_PURCHASE_P5B_FINALIZATION",message:"PASS",purchaseNumber:retry.purchaseNumber};
}
function runCanonicalPurchaseP5BWithStatus_(name, fn){const key="CANONICAL_PURCHASE:P5B:"+name,store=PropertiesService.getScriptProperties();store.setProperty(key,JSON.stringify({status:"RUNNING"}));try{const result=fn();store.setProperty(key,JSON.stringify({status:"PASS",result:result}));return result;}catch(error){store.setProperty(key,JSON.stringify({status:"FAIL",error:String(error.message||error)}));throw error;}}
function getCanonicalPurchaseP5BStatusCli(name){const raw=PropertiesService.getScriptProperties().getProperty("CANONICAL_PURCHASE:P5B:"+name);return raw?JSON.parse(raw):{status:"NOT_RUN"};}
function runCanonicalPurchaseP5BProductionWithStatusCli(){return runCanonicalPurchaseP5BWithStatus_("PRODUCTION",runCanonicalPurchaseP5BProductionRegressionCli);}
function runCanonicalPurchaseP5BFinalizationWithStatusCli(){return runCanonicalPurchaseP5BWithStatus_("FINALIZATION",runCanonicalPurchaseP5BFinalizationRecoveryCli);}
function runCanonicalPurchaseP5BParallelWorkerCli(submissionId, barangId, quantity){return submitPurchase({submissionId:String(submissionId),supplier:"P5B_PARALLEL",noFaktur:"P5B_PARALLEL",admin:"P5B_TEST",keterangan:"P5B true parallel",items:[{kodeBarang:String(barangId),qty:Number(quantity),hargaBeli:10000}]});}
function inspectCanonicalPurchaseP5BParallelCli(submissionId){const header=PurchaseRepository.findBySubmissionId(String(submissionId));if(!header)return {found:false};const details=PurchaseRepository.findItemsByPurchaseNumber(header.purchaseNumber),ledgers=details.map(function(detail){return StockLedgerRepository.findByReferensiFresh(detail.lineId);});return {found:true,purchaseNumber:header.purchaseNumber,status:header.status,detailCount:details.length,ledgerCount:ledgers.reduce(function(total,rows){return total+rows.length;},0),submissionId:header.submissionId};}
function cleanupCanonicalPurchaseP5BParallelCli(submissionId){const header=PurchaseRepository.findBySubmissionId(String(submissionId));if(!header)throw new Error("Fixture parallel P5B tidak ditemukan.");const details=PurchaseRepository.findItemsByPurchaseNumber(header.purchaseNumber);canonicalPurchaseP5BCleanup_(header.purchaseNumber,details);return {success:true,purchaseNumber:header.purchaseNumber};}
function runCanonicalPurchaseP5BPreparationWorkerCli(submissionId,barangId,quantity){return prepareCanonicalPurchaseSubmission({submissionId:String(submissionId),supplier:"P5B_PREP",noFaktur:"P5B_PREP",admin:"P5B_TEST",keterangan:"P5B preparation parallel",items:[{kodeBarang:String(barangId),qty:Number(quantity),hargaBeli:10000}]});}
function auditCanonicalPurchaseP5BFixturesCli(){const submissions=["P5B-PAR-176878","P5B-PAR-176879","P5B-PAR-176881","P5B-CONFLICT-176882","P5B-PAR-176883"];return {stock:BarangRepository.getStock("BRG000001"),fixtures:submissions.map(function(submissionId){const records=PurchaseRepository.findAllBySubmissionId(submissionId);return {submissionId:submissionId,property:PropertiesService.getScriptProperties().getProperty(CanonicalPurchasePreparationService.getPropertyKey_(submissionId)),purchases:records.map(function(record){const details=PurchaseRepository.findItemsByPurchaseNumber(record.purchaseNumber),ledgers=details.reduce(function(all,detail){return all.concat(StockLedgerRepository.findByReferensiFresh(detail.lineId).filter(function(row){return String(row[COL_STOK.JENISMUTASI]||"").trim()===MovementType.PURCHASE;}));},[]);return {purchaseNumber:record.purchaseNumber,status:record.status,transactionId:record.transactionId,idempotencyKey:record.idempotencyKey,payloadFingerprint:record.payloadFingerprint,details:details.map(function(d){return {barangId:d.kodeBarang,qty:d.qty,lineId:d.lineId};}),ledgerIds:ledgers.map(function(row){return row[COL_STOK.ID];}),contribution:ledgers.filter(function(row){return String(row[COL_STOK.BARANG_ID])==="BRG000001";}).reduce(function(total,row){return total+Number(row[COL_STOK.QTYMASUK]||0);},0)};})};})};}
function auditCanonicalPurchaseP5BFixturesJsonCli(){return JSON.stringify(auditCanonicalPurchaseP5BFixturesCli());}
function getCanonicalPurchaseP5BFreshStockCli(){return {barangId:"BRG000001",stock:BarangRepository.getStock("BRG000001")};}
function canonicalPurchaseP5BRun_(name,fn){return runCanonicalPurchaseP5BWithStatus_(name,fn);}
function testCanonicalPurchaseP5BNewOneLine_(){const b=canonicalPurchaseP5BBarang_(1)[0],before=canonicalPurchaseP5BSnapshot_([b]),p=canonicalPurchaseP5BPayload_("NEW",[{kodeBarang:b,qty:1,hargaBeli:10000}]),r=submitPurchase(p),after=canonicalPurchaseP5BSnapshot_([b]);canonicalPurchaseP5BAssert_(r.status===PurchaseStatus.POSTED&&after.headers===before.headers+1&&after.details===before.details+1&&after.ledger===before.ledger+1&&after.stocks[0]===before.stocks[0]+1,"New one-line gagal.");return {success:true,submissionId:p.submissionId,purchaseNumber:r.purchaseNumber,barangId:b,qtyContribution:1};}
function testCanonicalPurchaseP5BSameSubmissionRetry_(){const b=canonicalPurchaseP5BBarang_(1)[0],p=canonicalPurchaseP5BPayload_("RETRY",[{kodeBarang:b,qty:1,hargaBeli:10000}]),before=canonicalPurchaseP5BSnapshot_([b]),a=submitPurchase(p),r=submitPurchase(p),after=canonicalPurchaseP5BSnapshot_([b]);canonicalPurchaseP5BAssert_(a.purchaseNumber===r.purchaseNumber&&r.alreadyRecorded&&after.headers===before.headers+1&&after.ledger===before.ledger+1&&after.stocks[0]===before.stocks[0]+1,"Retry gagal.");return {success:true,submissionId:p.submissionId,purchaseNumber:a.purchaseNumber,barangId:b,qtyContribution:1};}
function testCanonicalPurchaseP5BConflict_(kind){const ids=canonicalPurchaseP5BBarang_(2),p=canonicalPurchaseP5BPayload_(kind,[{kodeBarang:ids[0],qty:1,hargaBeli:10000}]);submitPurchase(p);const before=canonicalPurchaseP5BSnapshot_(ids);if(kind==="QTY")p.items[0].qty=9;else if(kind==="BARANG")p.items[0].kodeBarang=ids[1];else p.supplier="P5B_CHANGED";let rejected=false;try{submitPurchase(p);}catch(e){rejected=String(e.message).indexOf("conflict")>=0;}canonicalPurchaseP5BAssert_(rejected&&JSON.stringify(before)===JSON.stringify(canonicalPurchaseP5BSnapshot_(ids)),"Conflict "+kind+" gagal.");return {success:true,submissionId:p.submissionId,qtyContribution:1};}
function testCanonicalPurchaseP5BDuplicate_(){const b=canonicalPurchaseP5BBarang_(1)[0],p=canonicalPurchaseP5BPayload_("DUP",[{kodeBarang:b,qty:2,hargaBeli:10000},{kodeBarang:b,qty:3,hargaBeli:10000}]),r=submitPurchase(p),d=PurchaseRepository.findItemsByPurchaseNumber(r.purchaseNumber);canonicalPurchaseP5BAssert_(d.length===2&&r.ledgerIds.length===2,"Duplicate gagal.");return {success:true,submissionId:p.submissionId,purchaseNumber:r.purchaseNumber,barangId:b,qtyContribution:5};}
function runCanonicalPurchaseP5BNewOneLineCli(){return canonicalPurchaseP5BRun_("NEW_ONE_LINE",testCanonicalPurchaseP5BNewOneLine_);}function runCanonicalPurchaseP5BSameSubmissionRetryCli(){return canonicalPurchaseP5BRun_("SAME_SUBMISSION_RETRY",testCanonicalPurchaseP5BSameSubmissionRetry_);}function runCanonicalPurchaseP5BConflictQtyCli(){return canonicalPurchaseP5BRun_("CONFLICT_QTY",function(){return testCanonicalPurchaseP5BConflict_("QTY");});}function runCanonicalPurchaseP5BConflictBarangCli(){return canonicalPurchaseP5BRun_("CONFLICT_BARANG",function(){return testCanonicalPurchaseP5BConflict_("BARANG");});}function runCanonicalPurchaseP5BConflictHeaderCli(){return canonicalPurchaseP5BRun_("CONFLICT_HEADER",function(){return testCanonicalPurchaseP5BConflict_("HEADER");});}function runCanonicalPurchaseP5BDuplicateBarangCli(){return canonicalPurchaseP5BRun_("DUPLICATE_BARANG",testCanonicalPurchaseP5BDuplicate_);}
function testCanonicalPurchaseP5BInventoryFailureRollback_(){const b=canonicalPurchaseP5BBarang_(1)[0],p=canonicalPurchaseP5BPayload_("INVENTORY_ROLLBACK",[{kodeBarang:b,qty:1,hargaBeli:10000}]),before=canonicalPurchaseP5BSnapshot_([b]);CanonicalPurchaseInventoryService.setTestHooksForTest_({beforeStockUpdate:function(){throw new Error("P5B forced inventory failure");}});let failed=false;try{submitPurchase(p);}catch(e){failed=String(e.message).indexOf("rollback")>=0;}finally{CanonicalPurchaseInventoryService.setTestHooksForTest_(null);}const after=canonicalPurchaseP5BSnapshot_([b]),doc=PurchaseRepository.findBySubmissionId(p.submissionId);canonicalPurchaseP5BAssert_(failed&&doc.status===PurchaseStatus.FAILED&&after.stocks[0]===before.stocks[0]&&after.ledger===before.ledger,"Inventory rollback gagal.");return {success:true,submissionId:p.submissionId,purchaseNumber:doc.purchaseNumber,stockContribution:0,ledgerContribution:0};}
function testCanonicalPurchaseP5BSecondLedgerFailureRollback_(){const b=canonicalPurchaseP5BBarang_(1)[0],p=canonicalPurchaseP5BPayload_("LEDGER_ROLLBACK",[{kodeBarang:b,qty:2,hargaBeli:10000},{kodeBarang:b,qty:3,hargaBeli:10000}]),before=canonicalPurchaseP5BSnapshot_([b]);CanonicalPurchaseInventoryService.setTestHooksForTest_({beforeLedgerWrite:function(line,index){if(index===1)throw new Error("P5B forced second ledger failure");}});let failed=false;try{submitPurchase(p);}catch(e){failed=String(e.message).indexOf("rollback")>=0;}finally{CanonicalPurchaseInventoryService.setTestHooksForTest_(null);}const after=canonicalPurchaseP5BSnapshot_([b]),doc=PurchaseRepository.findBySubmissionId(p.submissionId);canonicalPurchaseP5BAssert_(failed&&doc.status===PurchaseStatus.FAILED&&after.stocks[0]===before.stocks[0]&&after.ledger===before.ledger,"Second ledger rollback gagal.");return {success:true,submissionId:p.submissionId,purchaseNumber:doc.purchaseNumber,stockContribution:0,ledgerContribution:0};}
function runCanonicalPurchaseP5BInventoryFailureRollbackCli(){return canonicalPurchaseP5BRun_("INVENTORY_FAILURE_ROLLBACK",testCanonicalPurchaseP5BInventoryFailureRollback_);}function runCanonicalPurchaseP5BSecondLedgerFailureRollbackCli(){return canonicalPurchaseP5BRun_("SECOND_LEDGER_FAILURE_ROLLBACK",testCanonicalPurchaseP5BSecondLedgerFailureRollback_);}
function canonicalPurchaseP5BHeaderConflictSnapshot_(barangId,purchaseNumber){const details=purchaseNumber?PurchaseRepository.findItemsByPurchaseNumber(purchaseNumber):[],ledgerCount=details.reduce(function(total,detail){return total+StockLedgerRepository.findByReferensiFresh(detail.lineId).filter(function(row){return String(row[COL_STOK.JENISMUTASI]||"").trim()===MovementType.PURCHASE;}).length;},0),record=purchaseNumber?PurchaseRepository.findByPurchaseNumber(purchaseNumber):null;return {headerCount:PurchaseRepository.getHeaderSheet().getLastRow(),detailCount:PurchaseRepository.getDetailSheet().getLastRow(),purchaseStatus:record?record.status:null,stock:BarangRepository.getStock(barangId),stockLedgerRowCount:StockLedgerRepository.sheet().getLastRow(),canonicalPurchaseLedgerCount:ledgerCount};}
function runCanonicalPurchaseP5BConflictHeaderCli(){const key="CANONICAL_PURCHASE:P5B:CONFLICT_HEADER",store=PropertiesService.getScriptProperties(),b=canonicalPurchaseP5BBarang_(1)[0],p=canonicalPurchaseP5BPayload_("HEADER",[{kodeBarang:b,qty:1,hargaBeli:10000}]),diagnostic={submissionId:p.submissionId,originalSupplier:p.supplier,changedSupplier:"P5B_CHANGED"};try{const first=submitPurchase(p),record=PurchaseRepository.findByPurchaseNumber(first.purchaseNumber);diagnostic.purchaseNumber=first.purchaseNumber;diagnostic.originalFingerprint=record.payloadFingerprint;diagnostic.before=canonicalPurchaseP5BHeaderConflictSnapshot_(b,first.purchaseNumber);p.supplier=diagnostic.changedSupplier;diagnostic.changedFingerprint=CanonicalPurchasePreparationService.fingerprint_(p);let error=null;try{submitPurchase(p);}catch(e){error=e;diagnostic.conflictCaught=String(e.message||e).toLowerCase().indexOf("conflict")>=0;diagnostic.conflictMessage=String(e.message||e);}diagnostic.after=canonicalPurchaseP5BHeaderConflictSnapshot_(b,first.purchaseNumber);canonicalPurchaseP5BAssert_(diagnostic.originalFingerprint!==diagnostic.changedFingerprint,"Header fingerprint tidak berubah.");canonicalPurchaseP5BAssert_(diagnostic.conflictCaught===true,"Header conflict tidak tertangkap: "+String(diagnostic.conflictMessage));canonicalPurchaseP5BAssert_(diagnostic.before.headerCount===diagnostic.after.headerCount,"Header count berubah.");canonicalPurchaseP5BAssert_(diagnostic.before.detailCount===diagnostic.after.detailCount,"Detail count berubah.");canonicalPurchaseP5BAssert_(diagnostic.before.stock===diagnostic.after.stock,"Stock berubah.");canonicalPurchaseP5BAssert_(diagnostic.before.stockLedgerRowCount===diagnostic.after.stockLedgerRowCount&&diagnostic.before.canonicalPurchaseLedgerCount===diagnostic.after.canonicalPurchaseLedgerCount,"Ledger berubah.");canonicalPurchaseP5BAssert_(record.payloadFingerprint===diagnostic.originalFingerprint&&record.status===PurchaseStatus.POSTED,"Purchase original berubah.");store.setProperty(key,JSON.stringify({status:"PASS",result:diagnostic}));return {success:true,submissionId:p.submissionId,purchaseNumber:first.purchaseNumber,qtyContribution:1};}catch(e){diagnostic.failurePoint=String(e.message||e);store.setProperty(key,JSON.stringify({status:"FAIL",result:diagnostic}));throw e;}}
